/* ═══════════════════════════════════════════════════════════
   situations-data.js — Contenido de la sección "Situaciones"
   ═══════════════════════════════════════════════════════════
   Dos cosas viven aquí (nunca lógica, solo datos):

   1) SITUATIONS — las 8 situaciones reales, cada una ligada 1 a 1 a un
      fondo en assets/backgroundsituations/<bg>.png y a un "role" que la
      IA interpreta en "Practicar con IA".

   2) window.SITUATION_LESSON_BANKS — banco de mini-lecciones contextuales
      para el botón "Enséñame primero", con el MISMO formato que
      js/lessons-data/<code>.js (ver README ahí) para que reutilicen
      100% el motor existente (LessonEngine) sin tocarlo.
      Estructura: SITUATION_LESSON_BANKS.<LANG_CODE>.<situationKey> = [...]
      Por ahora solo hay contenido completo para EN (inglés) — el motor
      ya maneja con gracia los idiomas sin contenido todavía (ver
      getSituationLessons en situations.js), igual que renderLessons()
      hace con js/lessons-data/. Para añadir otro idioma: copia el bloque
      de EN, tradúcelo/adáptalo y regístralo bajo el código correspondiente
      (ES/FR/DE/IT/PT) — no hace falta tocar ningún motor.
   ═══════════════════════════════════════════════════════════ */

const SITUATIONS = [
  {
    key:'airport', icon:'✈️', name:'Aeropuerto', desc:'Check-in, seguridad y vuelos',
    level:'easy', bg:'assets/backgroundsituations/airport.png',
    role:'an airport check-in / gate agent', roleLabel:'un agente de aeropuerto',
    prompt:'You are an airport agent (check-in desk, security or gate). Help the learner check in, clear security, find a gate, or solve a flight problem. Speak in {LANG}.',
    steps:['Encontrar el mostrador correcto','Hacer check-in y facturar equipaje','Pasar el control de seguridad','Ubicar tu puerta de embarque'],
    phrases:['I would like to check in, please.','Where is the security checkpoint?','Which gate does my flight leave from?','My flight has been delayed. What should I do?'],
  },
  {
    key:'restaurant', icon:'🍽️', name:'Restaurante', desc:'Pedir, alergias y la cuenta',
    level:'easy', bg:'assets/backgroundsituations/restaurant.png',
    role:'a restaurant server/waiter', roleLabel:'un camarero',
    prompt:'You are a restaurant server. Help the learner get a table, order food, ask about ingredients/allergies, and pay. Speak in {LANG}.',
    steps:['Pedir una mesa','Preguntar por el menú y los platos','Hacer el pedido','Pedir la cuenta y pagar'],
    phrases:['Could I see the menu, please?','Does this contain nuts?','I would like to order this.','Could we have the bill, please?'],
  },
  {
    key:'hotel', icon:'🏨', name:'Hotel', desc:'Check-in y solicitudes',
    level:'easy', bg:'assets/backgroundsituations/hotel.png',
    role:'a hotel receptionist', roleLabel:'un recepcionista de hotel',
    prompt:'You are a hotel receptionist. Help the learner check in/out and resolve practical requests (towels, breakfast, wifi, problems with the room). Speak in {LANG}.',
    steps:['Confirmar la reserva','Hacer el check-in y recibir la llave','Pedir algo que necesitas','Resolver un problema con la habitación'],
    phrases:['I have a reservation under my name.','What time is breakfast?','Could I have an extra towel?','There is a problem with my room.'],
  },
  {
    key:'market', icon:'🛒', name:'Mercado', desc:'Precios, cantidades y regateo',
    level:'med', bg:'assets/backgroundsituations/market.png',
    role:'a market/shop vendor', roleLabel:'un vendedor de mercado',
    prompt:'You are a friendly market vendor selling food or goods. Help the learner ask for products, quantities, prices, and negotiate a little. Speak in {LANG}.',
    steps:['Preguntar por un producto','Preguntar el precio','Pedir una cantidad o pedir un descuento','Pagar y despedirte'],
    phrases:['How much does this cost?','Could you give me a discount?','I would like two kilos, please.','Do you accept cards?'],
  },
  {
    key:'hospital', icon:'🏥', name:'Hospital', desc:'Describir síntomas y citas',
    level:'med', bg:'assets/backgroundsituations/hospital.png',
    role:'a receptionist, nurse or doctor at a hospital', roleLabel:'personal de un hospital',
    prompt:'You are hospital staff (receptionist, nurse, or doctor). Help the learner book an appointment, describe non-emergency symptoms, and understand next steps. Speak in {LANG}. Do not diagnose; encourage urgent local care for real emergencies.',
    steps:['Pedir una cita','Describir tu síntoma','Decir desde cuándo lo tienes','Entender las indicaciones'],
    phrases:['I need to see a doctor.','I have had this pain for two days.','I am allergic to this medicine.','Is this an emergency?'],
  },
  {
    key:'office', icon:'💼', name:'Oficina', desc:'Compañeros, tareas y reuniones',
    level:'med', bg:'assets/backgroundsituations/office.png',
    role:'a coworker, client or boss in an office', roleLabel:'un compañero de oficina',
    prompt:'You are a coworker, client, or boss in an office setting. Have a natural work conversation: ask for help, discuss a deadline, propose a meeting, or give a quick update. Speak in {LANG}.',
    steps:['Saludar y dar contexto','Pedir ayuda o dar una actualización','Hablar de plazos o próximos pasos','Cerrar la conversación'],
    phrases:['Could you help me with this?','When is the deadline?','Can we schedule a meeting?','I will send you the report today.'],
  },
  {
    key:'party', icon:'🎉', name:'Fiesta', desc:'Conversación casual y small talk',
    level:'med', bg:'assets/backgroundsituations/party.png',
    role:'another guest at a party', roleLabel:'un invitado en una fiesta',
    prompt:'You met the learner at a social event/party. Have a natural, friendly conversation, make small talk, and introduce light social challenges. Speak in {LANG}.',
    steps:['Saludar y romper el hielo','Preguntar cómo conoce al anfitrión','Hablar de intereses en común','Despedirte con cortesía'],
    phrases:['How do you know the host?','What do you like to do in your free time?','That sounds interesting!','It was lovely talking to you.'],
  },
  {
    key:'university', icon:'🎓', name:'Universidad', desc:'Matrícula, clases y trámites',
    level:'hard', bg:'assets/backgroundsituations/university.png',
    role:'a university student, professor or administrative staff member', roleLabel:'un miembro de la universidad',
    prompt:'You are a university student, professor, or administrative staff member. Help the learner ask about enrollment, classes, deadlines, or campus life. Speak in {LANG}.',
    steps:['Explicar qué necesitas','Preguntar por requisitos o plazos','Elegir una opción o curso','Confirmar los siguientes pasos'],
    phrases:['I would like information about this course.','What are the entry requirements?','When does enrollment close?','Could you explain the schedule?'],
  },
];

function getSituation(key){ return SITUATIONS.find(s=>s.key===key) || null; }

/* ═══════════════════════════════════════════════════════════
   BANCO DE LECCIONES POR SITUACIÓN — INGLÉS (EN)
   Mismo formato exacto que js/lessons-data/en.js (ver buildLessons()
   en lessons.js). IDs prefijados con "sit_" para nunca chocar con el
   banco de lecciones normal del idioma.
   ═══════════════════════════════════════════════════════════ */
window.SITUATION_LESSON_BANKS = window.SITUATION_LESSON_BANKS || {};
window.SITUATION_LESSON_BANKS.EN = {

  airport: [
    { id:'sit_airport_vocab', level:'A1', title:'Vocabulario del aeropuerto', emoji:'🧳', xp:25,
      description:'Las palabras que verás y escucharás antes de volar.',
      study:{ vocab:[
        ['Check-in','Facturación','Donde entregas tu equipaje y recibes tu tarjeta de embarque.'],
        ['Boarding pass','Tarjeta de embarque'],
        ['Gate','Puerta de embarque'],
        ['Luggage / Baggage','Equipaje'],
        ['Security checkpoint','Control de seguridad'],
        ['Passport control','Control de pasaportes'],
      ]},
      ex:[
        ['mcq','¿Cómo se dice "tarjeta de embarque" en inglés?',['Boarding pass','Check-in','Gate','Passport'],0,'"Boarding pass" es el documento que te dejan subir al avión.','🧳 Estás en el mostrador de la aerolínea.'],
        ['fill','"Where is the security ___?"',['checkpoint','gate','luggage','pass'],0,'"Security checkpoint" es el punto donde revisan tu equipaje de mano.'],
        ['mcq','¿Qué palabra usarías para tu maleta?',['Luggage','Gate','Ticket','Desk'],0,'"Luggage" (o "baggage") se refiere a las maletas que llevas.'],
        ['translate','Traduce: "control de pasaportes"',['Passport control','Boarding pass','Security check','Baggage claim'],0,'"Passport control" es donde revisan tu documento de identidad al viajar.'],
        ['arrange','Ordena: [is / boarding / where / my / pass]',['Where is my boarding pass','Boarding is where my pass','My pass is where boarding','Pass boarding where is my'],0,'"Where is my boarding pass?" — pregunta muy común si la pierdes de vista.'],
      ],
    },
    { id:'sit_airport_phrases', level:'A1', title:'Frases para el check-in', emoji:'💬', xp:25,
      description:'Lo esencial para facturar y pasar seguridad sin problemas.',
      study:{ vocab:[
        ['I would like to check in, please.','Quisiera hacer el check-in, por favor.'],
        ['Do you have any bags to check?','¿Tiene equipaje para facturar?'],
        ['Window or aisle seat?','¿Asiento de ventanilla o pasillo?'],
        ['Which gate does my flight leave from?','¿De qué puerta sale mi vuelo?'],
        ['My flight has been delayed.','Mi vuelo se ha retrasado.'],
      ]},
      ex:[
        ['mcq','Quieres empezar el check-in. ¿Qué dices?',['I would like to check in, please.','I am from Spain.','See you later.','This is delicious.'],0,'Es la forma educada y directa de empezar el trámite.','🧳 Llegas al mostrador de tu aerolínea.'],
        ['mcq','El agente te pregunta "Window or aisle seat?". ¿De qué habla?',['Del tipo de asiento','Del equipaje','De la hora del vuelo','Del destino'],0,'Te está preguntando si prefieres asiento de ventanilla o de pasillo.'],
        ['fill','"Which ___ does my flight leave from?"',['gate','luggage','check-in','ticket'],0,'Preguntas por la puerta de embarque para saber a dónde ir.'],
        ['translate','Traduce: "Mi vuelo se ha retrasado."',['My flight has been delayed.','My flight has landed.','My flight is full.','My flight is cheap.'],0,'"Delayed" significa retrasado — muy útil si cambia tu horario.'],
        ['mcq','El agente pregunta "Do you have any bags to check?". ¿Qué te está preguntando?',['Si tienes equipaje para facturar','Si tienes pasaporte','Si tienes hambre','Si tienes reserva de hotel'],0,'"Bags to check" son las maletas que van a la bodega del avión.'],
      ],
    },
    { id:'sit_airport_dialogue', level:'A1', title:'Diálogo: en el mostrador', emoji:'🛂', xp:30,
      description:'Sigue una conversación real de check-in y practica tu respuesta.',
      study:{ grammar:[
        ['Preguntas con "Could you...?"','Forma educada de pedir algo. "Could you..." siempre va seguido del verbo en infinitivo sin "to".','Could you repeat that, please? → ¿Podría repetir eso, por favor?'],
      ]},
      ex:[
        ['mcq','Agente: "Passport, please." Tú respondes dándoselo. ¿Qué NO deberías decir?',['I do not have one.','Here you go.','Of course.','Here it is.'],0,'Si no tienes pasaporte no podrías facturar — en un check-in real siempre lo tendrías a mano.','🎬 Diálogo — Agente: "Passport, please."'],
        ['mcq','Agente: "Your flight is boarding in 20 minutes, gate 14." ¿Qué acabas de entender?',['La puerta y el tiempo que falta para embarcar','El precio del vuelo','Tu asiento','El destino del vuelo'],0,'"Boarding in 20 minutes" = embarque en 20 minutos; "gate 14" es la puerta.','🎬 Diálogo — el agente te da la información final.'],
        ['fill','Tú preguntas: "Could you ___ that, please?" (no escuchaste bien la puerta)',['repeat','check','pay','book'],0,'"Could you repeat that, please?" es perfecto cuando no entiendes algo.'],
        ['translate','Traduce: "¿Podría decirme dónde está la puerta 14?"',['Could you tell me where gate 14 is?','Can I have a window seat?','Where can I buy a ticket?','Is my flight delayed?'],0,'Combina "Could you tell me...?" con la pregunta indirecta "where gate 14 is".'],
        ['speaking','Imagina que estás en el mostrador. Preséntate, di que quieres hacer el check-in y pregunta por tu puerta de embarque. (mínimo 25 palabras)',[],['check-in','gate','boarding pass','please'],'Una buena respuesta usa al menos "check-in", "gate" y una frase educada como "please" o "could you".'],
      ],
    },
    { id:'sit_airport_baggage', level:'A2', title:'Equipaje y facturación', emoji:'🧳', xp:25,
      description:'Qué decir cuando algo sale mal con tu maleta.',
      study:{ vocab:[
        ['Carry-on bag','Equipaje de mano'],
        ['Checked bag','Equipaje facturado'],
        ['Overweight','Con exceso de peso'],
        ['Fragile','Frágil'],
        ['Baggage claim','Recogida de equipaje'],
        ['Lost luggage','Equipaje perdido'],
      ]},
      ex:[
        ['mcq','Tu maleta pesa más de lo permitido. ¿Qué palabra describe esto?',['Overweight','Fragile','Carry-on','Lost'],0,'"Overweight" significa que el equipaje pesa más de lo permitido.','🧳 El agente pesa tu maleta.'],
        ['fill','"Where is ___ claim?" (para recoger tu maleta al llegar)',['baggage','carry-on','check-in','security'],0,'"Baggage claim" es la zona donde recoges las maletas facturadas.'],
        ['translate','Traduce: "Mi maleta contiene objetos frágiles."',['My bag contains fragile items.','My bag is overweight.','My bag is lost.','My bag is carry-on.'],0,'"Fragile items" son objetos que se pueden romper fácilmente.'],
        ['mcq','Llegas y tu maleta no aparece. ¿Qué dices?',['My luggage is lost.','My bag is overweight.','This is my carry-on.','Where is the gate?'],0,'"My luggage is lost" reporta que tu equipaje no llegó contigo.'],
      ],
    },
    { id:'sit_airport_security', level:'A2', title:'Seguridad y migración', emoji:'🛂', xp:25,
      description:'Lo que te preguntarán al pasar los controles.',
      study:{ vocab:[
        ['Metal detector','Detector de metales'],
        ['Take off your shoes','Quítate los zapatos'],
        ['Liquids','Líquidos'],
        ['Customs','Aduana'],
        ['Declare','Declarar'],
        ['Purpose of your visit','Motivo de tu visita'],
      ]},
      ex:[
        ['mcq','El oficial de seguridad te pide que hagas algo con tus zapatos. ¿Qué dice?',['Take off your shoes, please.','Declare your bags, please.','Show your visa, please.','Open your luggage, please.'],0,'"Take off your shoes" te pide que te quites los zapatos para el control.','🛂 Estás en el control de seguridad.'],
        ['fill','En migración preguntan: "What is the ___ of your visit?"',['purpose','customs','liquid','detector'],0,'"Purpose of your visit" pregunta si viajas por turismo, trabajo, etc.'],
        ['mcq','¿Qué debes hacer con los líquidos en el control de seguridad?',['Ponerlos en una bolsa transparente','Guardarlos en la maleta grande','Beberlos antes de pasar','Declararlos en aduana'],0,'Los líquidos suelen ir en una bolsa transparente aparte para el control.'],
        ['translate','Traduce: "No tengo nada que declarar."',['I have nothing to declare.','I have nothing to carry.','I have nothing overweight.','I have nothing checked.'],0,'"Nothing to declare" se usa en aduana cuando no llevas artículos restringidos.'],
      ],
    },
    { id:'sit_airport_delays', level:'A2', title:'Retrasos y cambios de vuelo', emoji:'⏰', xp:25,
      description:'Qué decir si tu vuelo cambia de última hora.',
      study:{ vocab:[
        ['Delayed','Retrasado'],
        ['Cancelled','Cancelado'],
        ['Rebook','Reprogramar'],
        ['Connecting flight','Vuelo de conexión'],
        ['Missed my flight','Perdí mi vuelo'],
        ['Next available flight','Próximo vuelo disponible'],
      ]},
      ex:[
        ['mcq','Anuncian que tu vuelo no va a salir hoy. ¿Qué palabra usan?',['Cancelled','Delayed','Boarding','Overweight'],0,'"Cancelled" significa que el vuelo no saldrá — necesitarás otro.','⏰ Miras la pantalla de salidas.'],
        ['fill','"My flight was cancelled. Can you ___ me on another one?"',['rebook','declare','claim','board'],0,'"Rebook" significa reservarte de nuevo en otro vuelo.'],
        ['mcq','Tu primer vuelo se retrasó y ahora puede que pierdas el segundo. ¿Cómo se llama ese segundo vuelo?',['Connecting flight','Checked bag','Boarding pass','Baggage claim'],0,'Un "connecting flight" es el vuelo de conexión al que debes llegar a tiempo.'],
        ['translate','Traduce: "¿Cuál es el próximo vuelo disponible a Madrid?"',['What is the next available flight to Madrid?','Where is my connecting flight?','Is my flight cancelled?','Where is baggage claim?'],0,'"Next available flight" pregunta por la siguiente opción de vuelo.'],
      ],
    },
    { id:'sit_airport_help', level:'B1', title:'Pedir ayuda y resolver problemas', emoji:'🆘', xp:30,
      description:'Practica cómo pedir ayuda cuando algo no sale como esperabas.',
      study:{ grammar:[
        ['"I am supposed to..." para explicar un plan roto','Se usa para decir lo que se suponía que iba a pasar (y no pasó). Muy útil para explicar un problema al personal del aeropuerto.','I am supposed to be on flight 204, but it was cancelled. → Se suponía que iba en el vuelo 204, pero se canceló.'],
      ]},
      ex:[
        ['mcq','Estás perdido en el aeropuerto y necesitas ayuda para llegar a tu puerta. ¿Qué dices?',['Excuse me, could you help me find my gate?','Excuse me, is this seat taken?','Excuse me, does this contain nuts?','Excuse me, what time is breakfast?'],0,'"Could you help me find...?" es la forma educada de pedir indicaciones.','🆘 Estás perdido cerca de las puertas de embarque.'],
        ['fill','"I am ___ to be on flight 204, but it was cancelled."',['supposed','delayed','boarding','declared'],0,'"I am supposed to be on..." explica cuál era tu plan original.'],
        ['translate','Traduce: "Perdí mi vuelo de conexión, ¿qué puedo hacer?"',['I missed my connecting flight, what can I do?','I lost my luggage, what can I do?','My flight is delayed, what can I do?','I need a wheelchair, what can I do?'],0,'"I missed my connecting flight" explica el problema con claridad.'],
        ['speaking','Simula que perdiste tu vuelo de conexión: explica el problema al personal y pregunta qué opciones tienes. (mínimo 25 palabras)',[],['missed','connecting flight','what can I do'],'Una buena respuesta explica el problema y pide opciones con claridad.'],
      ],
    },
  ],

  restaurant: [
    { id:'sit_restaurant_vocab', level:'A1', title:'Vocabulario del restaurante', emoji:'🍽️', xp:25,
      description:'Lo básico para pedir comida sin dudar.',
      study:{ vocab:[
        ['Menu','Menú/carta'],
        ['Reservation','Reserva'],
        ['Order','Pedido / pedir'],
        ['Bill / Check','La cuenta'],
        ['Waiter / Server','Camarero'],
        ['Allergy','Alergia'],
      ]},
      ex:[
        ['mcq','¿Cómo se dice "la cuenta" en inglés (EE.UU.)?',['The check','The menu','The order','The bill (UK)'],0,'En EE.UU. se dice "the check"; en Reino Unido, "the bill". Ambas son correctas.','🍽️ Terminaste de comer y quieres pagar.'],
        ['fill','"Do you have a ___?" (para reservar mesa)',['reservation','allergy','order','waiter'],0,'"Reservation" es la reserva que hiciste con antelación.'],
        ['translate','Traduce: "camarero"',['Waiter','Menu','Guest','Chef'],0,'"Waiter" (o "server", neutro en género) atiende tu mesa.'],
        ['mcq','Le dices al camarero que tienes una alergia. ¿Qué palabra usas?',['Allergy','Reservation','Bill','Menu'],0,'"I have a nut allergy" avisa de una alergia a los frutos secos, por ejemplo.'],
        ['arrange','Ordena: [please / menu / the / could / I / have]',['Could I have the menu, please','The menu could I have please','Please could the menu I have','Have I could the menu please'],0,'"Could I have the menu, please?" es la forma educada de pedir la carta.'],
      ],
    },
    { id:'sit_restaurant_phrases', level:'A1', title:'Frases para pedir', emoji:'💬', xp:25,
      description:'De sentarte a pagar, en cinco frases clave.',
      study:{ vocab:[
        ['A table for two, please.','Una mesa para dos, por favor.'],
        ['Could I see the menu, please?','¿Podría ver el menú, por favor?'],
        ['I will have the...','Voy a pedir el/la...'],
        ['Does this contain nuts?','¿Esto contiene frutos secos?'],
        ['Could we have the bill, please?','¿Nos trae la cuenta, por favor?'],
      ]},
      ex:[
        ['mcq','Llegas al restaurante sin reserva. ¿Qué dices primero?',['A table for two, please.','Does this contain nuts?','Could we have the bill?','I will have the pasta.'],0,'Lo primero es pedir mesa antes de sentarte a mirar el menú.','🍽️ Entras al restaurante con un amigo.'],
        ['fill','"I ___ have the salmon, please."',['will','am','do','have'],0,'"I will have the salmon" es la forma habitual de pedir un plato.'],
        ['mcq','Eres alérgico a los frutos secos. ¿Qué preguntas?',['Does this contain nuts?','Is this table free?','Could I see the menu?','Could we have the bill?'],0,'"Does this contain nuts?" confirma si el plato lleva frutos secos.'],
        ['translate','Traduce: "¿Nos trae la cuenta, por favor?"',['Could we have the bill, please?','Could I see the menu, please?','A table for two, please.','Is this seat taken?'],0,'"Could we have the bill, please?" es la forma educada de pedir la cuenta.'],
        ['mcq','El camarero pregunta "Anything to drink?". ¿De qué te pregunta?',['De bebidas','Del postre','De la mesa','De la propina'],0,'"Anything to drink?" = ¿algo para beber?'],
      ],
    },
    { id:'sit_restaurant_dialogue', level:'A1', title:'Diálogo: pedir la cena', emoji:'🗣️', xp:30,
      description:'Sigue un pedido completo de principio a fin.',
      study:{ grammar:[
        ['"I will have..." para pedir comida','Se usa "will have" (no "want") para sonar natural al pedir en un restaurante.','I will have the chicken, please. → Voy a pedir el pollo, por favor.'],
      ]},
      ex:[
        ['mcq','Camarero: "Good evening! Do you have a reservation?" ¿Qué te está preguntando?',['Si reservaste mesa','Si quieres el menú','Si vas a pagar con tarjeta','Si tienes alergias'],0,'"Do you have a reservation?" pregunta si reservaste con antelación.','🎬 Diálogo — llegas al restaurante por la noche.'],
        ['mcq','Camarero: "Are you ready to order?" ¿Cuál es tu mejor respuesta si aún no decides?',['Could we have a few more minutes, please?','A table for two, please.','Could we have the bill?','This is delicious!'],0,'"A few more minutes, please" pide tiempo educadamente.','🎬 Diálogo — todavía estás mirando el menú.'],
        ['fill','Camarero: "___ to drink?" Tú: "Just water, please."',['Anything','Something','Nothing','Everything'],0,'"Anything to drink?" es la pregunta estándar sobre bebidas.'],
        ['translate','Traduce: "Está delicioso, gracias."',['This is delicious, thank you.','This is expensive, thank you.','This is cold, thank you.','This is spicy, thank you.'],0,'Un buen cumplido para el chef: "This is delicious, thank you."'],
        ['writing','Escribe un pequeño diálogo (mínimo 25 palabras) donde pides una mesa, eliges un plato y pides la cuenta.',[],['table','menu','order','bill'],'Debe incluir al menos pedir mesa, elegir algo del menú y pedir la cuenta.'],
      ],
    },
    { id:'sit_restaurant_allergies', level:'A2', title:'Alergias y preferencias', emoji:'🥜', xp:25,
      description:'Cómo comunicar alergias o dietas especiales con seguridad.',
      study:{ vocab:[
        ['I am allergic to...','Soy alérgico/a a...'],
        ['Vegetarian / Vegan','Vegetariano / Vegano'],
        ['Gluten-free','Sin gluten'],
        ['Dairy','Lácteos'],
        ['Spicy','Picante'],
        ['Ingredients','Ingredientes'],
      ]},
      ex:[
        ['mcq','Eres alérgico a los lácteos. ¿Qué dices al camarero?',['I am allergic to dairy.','I am vegetarian.','I like spicy food.','I need the bill.'],0,'"I am allergic to dairy" avisa claramente de tu alergia.','🥜 El camarero toma tu pedido.'],
        ['fill','"Is this dish ___-free?" (para saber si no lleva gluten)',['gluten','dairy','spicy','vegan'],0,'"Gluten-free" significa que el plato no contiene gluten.'],
        ['mcq','No comes carne ni pescado, pero sí huevos y queso. ¿Qué eres?',['Vegetarian','Vegan','Allergic','Gluten-free'],0,'"Vegetarian" no come carne ni pescado, pero puede comer lácteos y huevos.'],
        ['translate','Traduce: "¿Cuáles son los ingredientes de este plato?"',['What are the ingredients in this dish?','Is this dish spicy?','Do you have vegan options?','Could I see the menu?'],0,'"What are the ingredients?" pregunta exactamente qué lleva el plato.'],
      ],
    },
    { id:'sit_restaurant_complaints', level:'A2', title:'Quejas con el pedido', emoji:'😕', xp:25,
      description:'Qué decir si algo llega mal o tarda demasiado.',
      study:{ vocab:[
        ['This is not what I ordered.','Esto no es lo que pedí.'],
        ['This is cold.','Esto está frío.'],
        ['We have been waiting a long time.','Llevamos mucho tiempo esperando.'],
        ['Could you take this back?','¿Podría llevárselo?'],
        ['undercooked / overcooked','poco hecho / muy hecho'],
      ]},
      ex:[
        ['mcq','Te trajeron un plato distinto al que pediste. ¿Qué dices?',['This is not what I ordered.','This is delicious.','Could I see the menu?','We have a reservation.'],0,'"This is not what I ordered" señala el error con claridad y cortesía.','😕 Miran el plato con confusión.'],
        ['fill','La comida llegó fría. Dices: "Excuse me, this is ___."',['cold','delicious','spicy','fresh'],0,'"This is cold" indica que la comida no está a la temperatura correcta.'],
        ['mcq','Llevas 40 minutos esperando tu pedido. ¿Qué dices al camarero?',['We have been waiting a long time.','This is delicious.','Could I see the menu?','Does this contain nuts?'],0,'"We have been waiting a long time" comunica la demora educadamente.'],
        ['translate','Traduce: "La carne está muy poco hecha."',['The meat is undercooked.','The meat is delicious.','The meat is cold.','The meat is spicy.'],0,'"Undercooked" significa que no está suficientemente cocinado.'],
      ],
    },
    { id:'sit_restaurant_paying', level:'A2', title:'Pagar la cuenta y propina', emoji:'💳', xp:25,
      description:'Cierra la comida sin dudas sobre el pago.',
      study:{ vocab:[
        ['Split the bill','Dividir la cuenta'],
        ['Separate checks','Cuentas separadas'],
        ['Tip / Gratuity','Propina'],
        ['Is service included?','¿El servicio está incluido?'],
        ['Card / Cash','Tarjeta / Efectivo'],
      ]},
      ex:[
        ['mcq','Van varios amigos y quieren pagar cada uno lo suyo. ¿Qué piden?',['Separate checks, please.','A table for two, please.','Is this fresh?','Could I see the menu?'],0,'"Separate checks" pide que cada persona reciba su propia cuenta.','💳 Terminan de comer y llega el camarero.'],
        ['fill','"Can we ___ the bill?" (pagar entre todos a partes iguales)',['split','declare','claim','check'],0,'"Split the bill" significa dividir el total entre todos.'],
        ['mcq','Quieres saber si ya incluye propina antes de dejar más dinero. ¿Qué preguntas?',['Is service included?','Is this table free?','Do you have vegan options?','Is this dish spicy?'],0,'"Is service included?" confirma si la propina ya está en la cuenta.'],
        ['translate','Traduce: "Pagaremos con tarjeta, gracias."',['We will pay by card, thank you.','We will split the bill, thank you.','We will leave a tip, thank you.','We will order more, thank you.'],0,'"Pay by card" indica el método de pago que van a usar.'],
      ],
    },
    { id:'sit_restaurant_recommend', level:'B1', title:'Pedir recomendaciones', emoji:'⭐', xp:30,
      description:'Practica cómo pedir consejo al camarero y decidir qué pedir.',
      study:{ grammar:[
        ['"What would you recommend?" para pedir consejo','Forma natural de pedir la opinión del camarero sobre qué elegir del menú.','What would you recommend for someone who loves spicy food? → ¿Qué recomendaría para alguien a quien le encanta lo picante?'],
      ]},
      ex:[
        ['mcq','No sabes qué pedir y quieres la opinión del camarero. ¿Qué dices?',['What would you recommend?','This is not what I ordered.','Could we have the bill?','Is this table free?'],0,'"What would you recommend?" pide una sugerencia directamente.','⭐ Miras el menú sin decidirte.'],
        ['fill','"What is the ___ dish here?" (el plato más pedido)',['most popular','most expensive','spiciest','freshest'],0,'"Most popular dish" pregunta cuál es el plato favorito de los clientes.'],
        ['translate','Traduce: "¿Qué recomendaría para alguien que no come picante?"',['What would you recommend for someone who does not like spicy food?','What is the most popular dish here?','Is this dish gluten-free?','Could we have separate checks?'],0,'Combina "What would you recommend for someone who...?" con la preferencia.'],
        ['speaking','Simula que le pides consejo al camarero sobre qué plato elegir, mencionando una preferencia o restricción tuya. (mínimo 25 palabras)',[],['recommend','would you','dish'],'Una buena respuesta pide una recomendación y menciona una preferencia clara.'],
      ],
    },
  ],

  hotel: [
    { id:'sit_hotel_vocab', level:'A1', title:'Vocabulario del hotel', emoji:'🏨', xp:25,
      description:'Palabras clave para tu estadía.',
      study:{ vocab:[
        ['Reservation','Reserva'],
        ['Check-in / Check-out','Entrada / Salida'],
        ['Room key / Key card','Llave / tarjeta de la habitación'],
        ['Front desk','Recepción'],
        ['Wake-up call','Llamada para despertar'],
        ['Towel','Toalla'],
      ]},
      ex:[
        ['mcq','¿Dónde pides ayuda en un hotel?',['Front desk','Gate','Menu','Checkpoint'],0,'"Front desk" es la recepción del hotel.','🏨 Llegas al lobby del hotel.'],
        ['fill','"I have a ___ under my name."',['reservation','towel','key','check-out'],0,'"Reservation" es tu reserva hecha previamente.'],
        ['translate','Traduce: "tarjeta de la habitación"',['Key card','Front desk','Wake-up call','Reservation'],0,'La "key card" abre la puerta de tu habitación.'],
        ['mcq','Quieres que te despierten a las 7am. ¿Qué pides?',['A wake-up call','A key card','A reservation','A towel'],0,'"A wake-up call" es una llamada del hotel para despertarte.'],
        ['arrange','Ordena: [is / what / time / check-out]',['What time is check-out','Check-out is what time','Time what is check-out','Is what time check-out'],0,'"What time is check-out?" pregunta la hora límite para dejar la habitación.'],
      ],
    },
    { id:'sit_hotel_phrases', level:'A1', title:'Frases para el check-in', emoji:'💬', xp:25,
      description:'Del mostrador a la habitación sin sorpresas.',
      study:{ vocab:[
        ['I have a reservation under my name.','Tengo una reserva a mi nombre.'],
        ['What time is breakfast?','¿A qué hora es el desayuno?'],
        ['Could I have an extra towel?','¿Podría darme una toalla extra?'],
        ['Is breakfast included?','¿El desayuno está incluido?'],
        ['There is a problem with my room.','Hay un problema con mi habitación.'],
      ]},
      ex:[
        ['mcq','Llegas a recepción para el check-in. ¿Qué dices primero?',['I have a reservation under my name.','There is a problem with my room.','What time is breakfast?','Could I have a towel?'],0,'Primero confirmas tu reserva para que te den la llave.','🏨 Llegas a la recepción del hotel.'],
        ['fill','"Is breakfast ___?"',['included','reserved','delayed','allergic'],0,'"Is breakfast included?" pregunta si ya está pagado con la habitación.'],
        ['mcq','El aire acondicionado no funciona. ¿Qué dices?',['There is a problem with my room.','What time is breakfast?','I have a reservation.','Could I have a towel?'],0,'Es la frase correcta para reportar un problema en la habitación.'],
        ['translate','Traduce: "¿Podría darme una toalla extra?"',['Could I have an extra towel, please?','Could I have a wake-up call?','Is breakfast included?','What time is check-out?'],0,'"Could I have...?" es la forma educada de pedir algo extra.'],
        ['mcq','Recepcionista: "Breakfast is from 7 to 10 in the lobby." ¿Qué acabas de entender?',['El horario y lugar del desayuno','El precio de la habitación','La hora de check-out','Tu número de habitación'],0,'Te está dando el horario (7 a 10) y el lugar (el lobby).'],
      ],
    },
    { id:'sit_hotel_dialogue', level:'A1', title:'Diálogo: en recepción', emoji:'🗝️', xp:30,
      description:'Practica un check-in completo con imprevistos.',
      study:{ grammar:[
        ['"There is / There are" para describir problemas','"There is" + singular, "There are" + plural. Útil para reportar algo que falta o no funciona.','There is a problem with the shower. → Hay un problema con la ducha.'],
      ]},
      ex:[
        ['mcq','Recepcionista: "Welcome! Do you have a reservation?" Tú respondes que sí, a tu nombre. ¿Qué dices?',['Yes, I have a reservation under my name.','No, I would like the menu.','Yes, this is delicious.','No, I need a doctor.'],0,'Confirmas la reserva usando "under my name".','🎬 Diálogo — check-in en el hotel.'],
        ['mcq','Recepcionista: "Here is your key card. Breakfast is from 7 to 10." ¿Qué información te dieron?',['La llave y el horario de desayuno','El precio de la habitación','La hora de salida','El número de tu vuelo'],0,'Te entregan la llave y te informan el horario del desayuno.','🎬 Diálogo — te dan la bienvenida.'],
        ['fill','En la habitación notas que falta jabón. Dices: "___ no soap in the bathroom."',['There is','There are','It has','I have'],0,'"There is no soap" — "soap" es incontable, por eso usamos "there is".'],
        ['translate','Traduce: "Hay un problema con la ducha."',['There is a problem with the shower.','There are two towels.','I have a reservation.','Is breakfast included?'],0,'"There is a problem with the shower" reporta el inconveniente correctamente.'],
        ['speaking','Simula que llegas a recepción: confirma tu reserva, pregunta el horario de desayuno y pide una toalla extra. (mínimo 25 palabras)',[],['reservation','breakfast','towel'],'Una buena respuesta incluye la reserva, el desayuno y la toalla extra.'],
      ],
    },
    { id:'sit_hotel_services', level:'A2', title:'Servicios del hotel', emoji:'🏊', xp:25,
      description:'Pregunta por todo lo que el hotel ofrece.',
      study:{ vocab:[
        ['Gym','Gimnasio'],
        ['Pool','Piscina'],
        ['Room service','Servicio a la habitación'],
        ['Laundry service','Servicio de lavandería'],
        ['Wi-Fi password','Contraseña del wifi'],
        ['Parking','Estacionamiento'],
      ]},
      ex:[
        ['mcq','Quieres nadar antes de cenar. ¿Qué preguntas?',['What time does the pool close?','What time is check-out?','Do you have room service?','Is there parking?'],0,'Preguntas por el horario de la piscina para planear tu tarde.','🏊 Miras el folleto de servicios del hotel.'],
        ['fill','"Could I get the Wi-Fi ___?"',['password','service','parking','laundry'],0,'"Wi-Fi password" es la contraseña para conectarte a internet.'],
        ['mcq','Quieres comer en tu habitación sin bajar al restaurante. ¿Qué pides?',['Room service','Laundry service','Parking','Gym access'],0,'"Room service" es el servicio de comida directamente en tu habitación.'],
        ['translate','Traduce: "¿Hay estacionamiento disponible?"',['Is there parking available?','Is there a pool?','Is there room service?','Is there a gym?'],0,'"Is there parking available?" pregunta por espacio para el auto.'],
      ],
    },
    { id:'sit_hotel_complaints', level:'A2', title:'Quejas y problemas', emoji:'🔧', xp:25,
      description:'Reporta problemas en tu habitación con seguridad.',
      study:{ vocab:[
        ['The AC is not working.','El aire acondicionado no funciona.'],
        ['The room is dirty.','La habitación está sucia.'],
        ['It is too noisy.','Hay demasiado ruido.'],
        ['Could you send someone to fix it?','¿Podría enviar a alguien a arreglarlo?'],
        ['Could I change rooms?','¿Podría cambiar de habitación?'],
      ]},
      ex:[
        ['mcq','Hace mucho calor y el aire acondicionado no enfría. ¿Qué dices?',['The AC is not working.','The room is dirty.','It is too noisy.','Could I change rooms?'],0,'"The AC is not working" reporta el problema exacto.','🔧 Llamas a recepción desde tu habitación.'],
        ['fill','"Could you send someone to ___ it?" (arreglar algo roto)',['fix','clean','change','book'],0,'"Fix it" pide que reparen lo que está fallando.'],
        ['mcq','Los vecinos hacen mucho ruido y no puedes dormir. ¿Qué dices?',['It is too noisy.','The room is dirty.','The AC is not working.','Could I get the Wi-Fi password?'],0,'"It is too noisy" comunica el problema del ruido.'],
        ['translate','Traduce: "¿Podría cambiarme de habitación, por favor?"',['Could I change rooms, please?','Could I get room service, please?','Could I have a wake-up call, please?','Could I use the pool, please?'],0,'"Could I change rooms?" pide una habitación diferente.'],
      ],
    },
    { id:'sit_hotel_checkout', level:'A2', title:'Check-out y cargos extra', emoji:'🧾', xp:25,
      description:'Revisa tu cuenta final sin sorpresas.',
      study:{ vocab:[
        ['Final bill','Cuenta final'],
        ['Extra charge','Cargo adicional'],
        ['Minibar','Minibar'],
        ['Late check-out','Salida tardía'],
        ['Receipt','Recibo'],
      ]},
      ex:[
        ['mcq','Ves un cargo que no reconoces en tu cuenta. ¿Qué dices?',['What is this extra charge for?','Could I have a wake-up call?','Is breakfast included?','Could I change rooms?'],0,'"What is this extra charge for?" pide una explicación del cargo.','🧾 Revisas la cuenta antes de pagar.'],
        ['fill','"Could I get a ___?" (para tener comprobante del pago)',['receipt','minibar','check-out','password'],0,'"Receipt" es el comprobante o recibo del pago.'],
        ['mcq','Quieres salir más tarde de lo normal sin pagar de más. ¿Qué pides?',['Late check-out','Room service','Extra towel','Wi-Fi password'],0,'"Late check-out" es salir más tarde de la hora habitual.'],
        ['translate','Traduce: "Creo que hay un error en mi cuenta."',['I think there is a mistake on my bill.','I think the room is dirty.','I think breakfast is included.','I think I need a taxi.'],0,'"There is a mistake on my bill" señala un posible error en el cobro.'],
      ],
    },
    { id:'sit_hotel_local', level:'B1', title:'Recomendaciones locales', emoji:'🗺️', xp:30,
      description:'Practica cómo pedir consejos sobre qué hacer en la ciudad.',
      study:{ grammar:[
        ['"Could you recommend...?" para pedir sugerencias','Forma educada de pedir consejo sobre lugares, restaurantes o actividades cercanas.','Could you recommend a good restaurant nearby? → ¿Podría recomendarme un buen restaurante cerca?'],
      ]},
      ex:[
        ['mcq','Quieres cenar bien esta noche cerca del hotel. ¿Qué preguntas en recepción?',['Could you recommend a good restaurant nearby?','Could I change rooms?','Is the pool open?','What is this extra charge?'],0,'"Could you recommend...?" pide una sugerencia directamente.','🗺️ Preguntas en recepción sobre la ciudad.'],
        ['fill','"How do I get ___ downtown?" (al centro de la ciudad)',['to','from','at','on'],0,'"Get to downtown" significa llegar al centro de la ciudad.'],
        ['translate','Traduce: "¿Qué debería visitar si solo tengo un día?"',['What should I visit if I only have one day?','What time does the pool close?','Could I get a receipt?','Is there parking available?'],0,'Pregunta por recomendaciones ajustadas al tiempo disponible.'],
        ['speaking','Simula que le pides al recepcionista una recomendación de un lugar para visitar y cómo llegar. (mínimo 25 palabras)',[],['recommend','how do I get','nearby'],'Una buena respuesta pide una recomendación y pregunta cómo llegar.'],
      ],
    },
  ],

  market: [
    { id:'sit_market_vocab', level:'A2', title:'Vocabulario del mercado', emoji:'🛒', xp:25,
      description:'Precios, cantidades y productos frescos.',
      study:{ vocab:[
        ['Price','Precio'],
        ['Discount','Descuento'],
        ['Fresh','Fresco'],
        ['Kilogram / pound','Kilogramo / libra'],
        ['Cash / Card','Efectivo / tarjeta'],
        ['Bargain','Negociar el precio / ganga'],
      ]},
      ex:[
        ['mcq','¿Cómo preguntas el precio de algo?',['How much does this cost?','Is this fresh?','Do you accept cards?','Could I have a bag?'],0,'"How much does this cost?" es la pregunta directa por el precio.','🛒 Estás frente a un puesto de frutas.'],
        ['fill','"Do you accept ___ or only cash?"',['cards','discounts','kilograms','bargains'],0,'Preguntas si aceptan tarjeta, en lugar de solo efectivo.'],
        ['translate','Traduce: "un kilo de tomates"',['A kilogram of tomatoes','A price of tomatoes','A discount on tomatoes','A bargain of tomatoes'],0,'"A kilogram of..." indica la cantidad que quieres comprar.'],
        ['mcq','El vendedor te ofrece bajar el precio. ¿Qué palabra usó probablemente?',['Discount','Fresh','Cash','Bargain (verbo)'],0,'"Discount" significa descuento sobre el precio original.'],
        ['arrange','Ordena: [me / could / a / discount / give / you]',['Could you give me a discount','You could give me a discount','Discount could you give me','Give me a discount could you'],0,'"Could you give me a discount?" es la forma educada de pedir rebaja.'],
      ],
    },
    { id:'sit_market_phrases', level:'A2', title:'Frases para comprar', emoji:'💬', xp:25,
      description:'De preguntar el precio a pagar.',
      study:{ vocab:[
        ['How much does this cost?','¿Cuánto cuesta esto?'],
        ['Could you give me a discount?','¿Podría hacerme un descuento?'],
        ['I would like two kilos, please.','Quisiera dos kilos, por favor.'],
        ['Do you accept cards?','¿Acepta tarjeta?'],
        ['Is this fresh?','¿Esto está fresco?'],
      ]},
      ex:[
        ['mcq','Quieres saber si la fruta llegó hoy. ¿Qué preguntas?',['Is this fresh?','Do you accept cards?','How much does this cost?','I would like two kilos.'],0,'"Is this fresh?" pregunta directamente por la frescura del producto.','🛒 Miras una caja de fresas.'],
        ['fill','"I would ___ two kilos, please."',['like','have','want to','need to'],0,'"I would like..." es la forma educada de pedir una cantidad.'],
        ['mcq','El vendedor dice el precio y te parece alto. ¿Qué le dices?',['Could you give me a discount?','Is this fresh?','Do you accept cards?','I would like two kilos.'],0,'Pides amablemente un descuento con "Could you give me a discount?"'],
        ['translate','Traduce: "¿Acepta tarjeta?"',['Do you accept cards?','Is this fresh?','How much does this cost?','Could I have a bag?'],0,'"Do you accept cards?" confirma el método de pago.'],
        ['mcq','Vendedor: "That will be five dollars." ¿Qué te está diciendo?',['El precio total','El descuento','La cantidad disponible','La hora de cierre'],0,'"That will be five dollars" indica cuánto debes pagar.'],
      ],
    },
    { id:'sit_market_dialogue', level:'A2', title:'Diálogo: en el puesto', emoji:'🗣️', xp:30,
      description:'Negocia un precio de principio a fin.',
      study:{ grammar:[
        ['Cantidades con "a kilo of / a bag of"','Para pedir cantidades usa "a [cantidad] of [producto]".','A kilo of apples, two bags of rice.'],
      ]},
      ex:[
        ['mcq','Vendedor: "These tomatoes are very fresh today." ¿Qué te dice?',['Que los tomates son frescos','Que los tomates son caros','Que no quedan tomates','Que hay descuento'],0,'"Very fresh today" resalta la frescura del producto.','🎬 Diálogo — señalas los tomates.'],
        ['mcq','Preguntas el precio y responde "Three dollars a kilo." Tú quieres 2 kilos. ¿Qué dices?',['I would like two kilos, please.','Is this fresh?','Do you accept cards?','Could I have a bag?'],0,'Confirmas la cantidad que quieres comprar.','🎬 Diálogo — ya sabes el precio por kilo.'],
        ['fill','Regateando, dices: "___ you give me a discount for two kilos?"',['Could','Is','Do','Have'],0,'"Could you give me a discount...?" es la forma educada de negociar.'],
        ['translate','Traduce: "Son cinco dólares en total."',['That is five dollars in total.','That is five kilos in total.','That is a discount of five.','That is fresh for five.'],0,'"That is five dollars in total" confirma el total a pagar.'],
        ['writing','Escribe un diálogo corto (mínimo 25 palabras) donde preguntas el precio, pides una cantidad y negocias un descuento.',[],['price','kilo','discount'],'Debe incluir preguntar el precio, pedir una cantidad y negociar.'],
      ],
    },
    { id:'sit_market_products', level:'A2', title:'Productos y sustitutos', emoji:'🔍', xp:25,
      description:'Qué decir cuando buscas algo específico.',
      study:{ vocab:[
        ['Do you have...?','¿Tiene...?'],
        ['Out of stock','Agotado'],
        ['Is there anything similar?','¿Hay algo parecido?'],
        ['Ripe / Unripe','Maduro / Verde (sin madurar)'],
        ['Organic','Orgánico'],
      ]},
      ex:[
        ['mcq','Buscas un producto específico que no ves en el puesto. ¿Qué preguntas?',['Do you have any mangoes?','How much does this cost?','Is this fresh?','Do you accept cards?'],0,'"Do you have...?" pregunta directamente si tienen ese producto.','🔍 Buscas un producto en el mercado.'],
        ['fill','El vendedor dice que ya no le queda. Usa la palabra: "___ of stock."',['Out','In','On','At'],0,'"Out of stock" significa que se acabó el producto.'],
        ['mcq','No encuentran lo que buscas, pero quieres una alternativa parecida. ¿Qué preguntas?',['Is there anything similar?','Is this organic?','Is this ripe?','How much is this?'],0,'"Is there anything similar?" pide una alternativa parecida.'],
        ['translate','Traduce: "¿Este aguacate está maduro?"',['Is this avocado ripe?','Is this avocado organic?','Is this avocado fresh?','Is this avocado cheap?'],0,'"Ripe" describe una fruta lista para comer.'],
      ],
    },
    { id:'sit_market_returns', level:'A2', title:'Quejas y devoluciones', emoji:'↩️', xp:25,
      description:'Qué hacer si un producto llega en mal estado.',
      study:{ vocab:[
        ['This is not fresh.','Esto no está fresco.'],
        ['Could I get a refund?','¿Podría darme un reembolso?'],
        ['Could I exchange this?','¿Podría cambiar esto?'],
        ['It is broken / damaged.','Está roto / dañado.'],
        ['Receipt','Recibo'],
      ]},
      ex:[
        ['mcq','Compraste fruta y al llegar a casa está en mal estado. ¿Qué dirías si regresas?',['This is not fresh.','This is a discount.','This is organic.','This is ripe.'],0,'"This is not fresh" señala el problema del producto.','↩️ Vuelves al puesto con la bolsa de compra.'],
        ['fill','"Could I get a ___?" (que te devuelvan el dinero)',['refund','discount','receipt','bag'],0,'"Refund" significa que te devuelvan el dinero pagado.'],
        ['mcq','Prefieres cambiar el producto por otro en vez de que te devuelvan el dinero. ¿Qué pides?',['Could I exchange this?','Could I get a refund?','Is this organic?','Do you have mangoes?'],0,'"Exchange" significa cambiar un producto por otro.'],
        ['translate','Traduce: "¿Tiene el recibo de la compra?"',['Do you have the receipt?','Do you have any mangoes?','Do you have a discount?','Do you have a bag?'],0,'El recibo suele pedirse para procesar una devolución o cambio.'],
      ],
    },
    { id:'sit_market_payment', level:'A2', title:'Formas de pago', emoji:'💰', xp:25,
      description:'Resuelve cualquier duda sobre cómo pagar.',
      study:{ vocab:[
        ['Cash only','Solo efectivo'],
        ['Do you have change?','¿Tiene cambio?'],
        ['Small bills','Billetes pequeños'],
        ['Contactless payment','Pago sin contacto'],
        ['Receipt, please.','El recibo, por favor.'],
      ]},
      ex:[
        ['mcq','El vendedor no acepta tarjeta. ¿Qué te dice?',['Cash only, please.','Card only, please.','Contactless only, please.','Discount only, please.'],0,'"Cash only" significa que solo aceptan pago en efectivo.','💰 Vas a pagar tu compra.'],
        ['fill','Pagas con un billete grande y preguntas: "Do you have ___?" (dinero de vuelta)',['change','cash','discount','receipt'],0,'"Change" es el dinero de vuelta cuando pagas con un billete grande.'],
        ['mcq','No tienes billetes pequeños y preguntas si hay problema. ¿Qué dices?',['I only have large bills, is that OK?','I only have small bills, is that OK?','I only have cards, is that OK?','I only have coins, is that OK?'],0,'Avisas de que solo tienes billetes grandes antes de pagar.'],
        ['translate','Traduce: "¿Puedo pagar sin contacto?"',['Can I pay contactless?','Can I pay in cash?','Can I get a discount?','Can I get a refund?'],0,'"Pay contactless" se refiere a pagar acercando la tarjeta o el teléfono.'],
      ],
    },
    { id:'sit_market_directions', level:'B1', title:'Indicaciones en el mercado', emoji:'🧭', xp:30,
      description:'Practica cómo orientarte dentro de un mercado grande.',
      study:{ grammar:[
        ['Preposiciones de lugar: "next to", "across from", "at the end of"','Se usan para explicar dónde está algo dentro de un espacio grande como un mercado.','The fish stand is next to the bakery. → El puesto de pescado está junto a la panadería.'],
      ]},
      ex:[
        ['mcq','No encuentras el puesto de especias. ¿Qué preguntas?',['Where can I find the spice stand?','How much does this cost?','Do you have change?','Is this organic?'],0,'"Where can I find...?" pregunta la ubicación de algo dentro del mercado.','🧭 Caminas entre los puestos buscando algo.'],
        ['fill','Te indican: "It is ___ to the bakery." (justo al lado)',['next','across','end','between'],0,'"Next to" significa justo al lado de algo.'],
        ['translate','Traduce: "Está al final de este pasillo."',['It is at the end of this aisle.','It is next to the entrance.','It is across from the exit.','It is between two stands.'],0,'"At the end of this aisle" indica que está al final del pasillo.'],
        ['speaking','Simula que preguntas cómo llegar a un puesto específico dentro del mercado y confirmas que entendiste bien las indicaciones. (mínimo 25 palabras)',[],['where can I find','next to','thank you'],'Una buena respuesta pregunta la ubicación y confirma haber entendido.'],
      ],
    },
  ],

  hospital: [
    { id:'sit_hospital_vocab', level:'A2', title:'Vocabulario del hospital', emoji:'🏥', xp:25,
      description:'Palabras esenciales para explicar cómo te sientes.',
      study:{ vocab:[
        ['Appointment','Cita'],
        ['Symptom','Síntoma'],
        ['Pain','Dolor'],
        ['Prescription','Receta médica'],
        ['Allergic','Alérgico/a'],
        ['Emergency','Emergencia'],
      ]},
      ex:[
        ['mcq','¿Cómo dirías que tienes dolor de cabeza?',['I have a headache.','I have an appointment.','I have a prescription.','I have an emergency.'],0,'"Headache" es dolor de cabeza; se usa con "I have a...".','🏥 Llegas a la recepción del hospital.'],
        ['fill','"I need to book an ___ with a doctor."',['appointment','allergy','emergency','pain'],0,'"Appointment" es la cita que reservas para ver al médico.'],
        ['translate','Traduce: "receta médica"',['Prescription','Appointment','Symptom','Pain'],0,'"Prescription" es lo que el médico te da para comprar medicinas.'],
        ['mcq','Eres alérgico a la penicilina. ¿Qué dices?',['I am allergic to penicillin.','I have an appointment.','This is an emergency.','I need a prescription.'],0,'"I am allergic to..." avisa de una alergia específica.'],
        ['arrange','Ordena: [is / this / an / emergency]',['Is this an emergency','This an emergency is','Emergency this is an','An emergency is this'],0,'"Is this an emergency?" pregunta si la situación requiere atención inmediata.'],
      ],
    },
    { id:'sit_hospital_phrases', level:'A2', title:'Frases para describir síntomas', emoji:'💬', xp:25,
      description:'Explica cómo te sientes con claridad.',
      study:{ vocab:[
        ['I need to see a doctor.','Necesito ver a un médico.'],
        ['I have had this pain for two days.','Tengo este dolor desde hace dos días.'],
        ['I am allergic to this medicine.','Soy alérgico/a a esta medicina.'],
        ['How often should I take this?','¿Cada cuánto debo tomar esto?'],
        ['Is this an emergency?','¿Esto es una emergencia?'],
      ]},
      ex:[
        ['mcq','Llegas a recepción sintiéndote mal. ¿Qué dices primero?',['I need to see a doctor.','How often should I take this?','Is this an emergency?','I am allergic to this medicine.'],0,'Es la frase inicial más natural para pedir atención médica.','🏥 Entras al hospital sintiéndote mal.'],
        ['fill','"I have ___ this pain for two days."',['had','have','having','has'],0,'"I have had this pain for two days" — usamos present perfect para algo que empezó en el pasado y continúa.'],
        ['mcq','El médico te da un medicamento nuevo. ¿Qué preguntas antes de tomarlo si eres alérgico a algo?',['I am allergic to this medicine.','I need to see a doctor.','Is this an emergency?','How often should I take this?'],0,'Avisas de la alergia ANTES de tomar cualquier medicamento nuevo.'],
        ['translate','Traduce: "¿Cada cuánto debo tomar esto?"',['How often should I take this?','How much does this cost?','Is this an emergency?','Do you accept cards?'],0,'"How often should I take this?" pregunta la frecuencia del medicamento.'],
        ['mcq','El médico dice "Take one pill every eight hours." ¿Qué acabas de entender?',['La frecuencia del medicamento','El precio del medicamento','La fecha de tu próxima cita','El nombre del medicamento'],0,'"Every eight hours" indica cada cuánto tiempo debes tomarlo.'],
      ],
    },
    { id:'sit_hospital_dialogue', level:'A2', title:'Diálogo: en recepción', emoji:'🗣️', xp:30,
      description:'Sigue una consulta sencilla de principio a fin.',
      study:{ grammar:[
        ['Present perfect para síntomas: "I have had..."','Se usa para algo que empezó en el pasado y sigue ahora. Muy común al describir síntomas.','I have had a fever since yesterday. → Tengo fiebre desde ayer.'],
      ]},
      ex:[
        ['mcq','Recepcionista: "What seems to be the problem?" ¿Qué te está preguntando?',['Cuál es tu síntoma o molestia','Tu nombre completo','Tu número de seguro','Tu hora de cita'],0,'"What seems to be the problem?" pregunta por tu malestar.','🎬 Diálogo — te reciben en el hospital.'],
        ['mcq','Tú: "I have had a headache since yesterday." ¿Qué acabas de decir?',['Que tienes dolor de cabeza desde ayer','Que tienes una cita mañana','Que eres alérgico a algo','Que es una emergencia'],0,'Describes desde cuándo tienes el síntoma con "since yesterday".','🎬 Diálogo — explicas tu malestar.'],
        ['fill','El médico pregunta: "Are you ___ to any medication?"',['allergic','emergency','symptom','appointment'],0,'"Are you allergic to...?" pregunta por alergias antes de recetar.'],
        ['translate','Traduce: "Necesito ver a un médico, por favor."',['I need to see a doctor, please.','I need a discount, please.','I need a table, please.','I need a room, please.'],0,'"I need to see a doctor, please" pide atención médica educadamente.'],
        ['speaking','Simula que describes un síntoma al médico: qué te duele, desde cuándo y si eres alérgico a algo. (mínimo 25 palabras)',[],['pain','since','allergic'],'Una buena respuesta menciona el síntoma, desde cuándo lo tienes y alergias si aplica.'],
      ],
    },
    { id:'sit_hospital_pharmacy', level:'A2', title:'En la farmacia', emoji:'💊', xp:25,
      description:'Vocabulario para comprar y entender medicamentos.',
      study:{ vocab:[
        ['Prescription','Receta médica'],
        ['Dosage','Dosis'],
        ['Side effects','Efectos secundarios'],
        ['Painkiller','Analgésico'],
        ['Twice a day','Dos veces al día'],
        ['On an empty stomach','En ayunas'],
      ]},
      ex:[
        ['mcq','El farmacéutico te pregunta si tienes una receta. ¿Qué palabra usa?',['Prescription','Dosage','Painkiller','Side effect'],0,'"Prescription" es el documento del médico para comprar ciertos medicamentos.','💊 Llegas al mostrador de la farmacia.'],
        ['fill','"Take one pill ___ a day." (dos veces)',['twice','once','never','always'],0,'"Twice a day" significa dos veces al día.'],
        ['mcq','Quieres saber si un medicamento puede darte mareo o sueño. ¿Qué preguntas?',['What are the side effects?','What is the dosage?','Is this a painkiller?','Do I need a prescription?'],0,'"Side effects" son las reacciones no deseadas de un medicamento.'],
        ['translate','Traduce: "¿Debo tomarlo en ayunas?"',['Should I take it on an empty stomach?','Should I take it twice a day?','Should I take it with a prescription?','Should I take a painkiller?'],0,'"On an empty stomach" significa sin haber comido antes.'],
      ],
    },
    { id:'sit_hospital_emergency', level:'B1', title:'Emergencias', emoji:'🚨', xp:30,
      description:'Frases clave si necesitas ayuda médica urgente.',
      study:{ vocab:[
        ['Call an ambulance!','¡Llame a una ambulancia!'],
        ['It is an emergency.','Es una emergencia.'],
        ['I can\'t breathe.','No puedo respirar.'],
        ['He/She is unconscious.','Está inconsciente.'],
        ['Chest pain','Dolor en el pecho'],
      ]},
      ex:[
        ['mcq','Alguien se desmaya cerca de ti y necesitas ayuda urgente. ¿Qué gritas?',['Call an ambulance!','Could I see the menu?','Is this fresh?','What is the dosage?'],0,'"Call an ambulance!" pide ayuda médica de emergencia inmediatamente.','🚨 Alguien necesita ayuda urgente cerca de ti.'],
        ['fill','"It is an ___!" (para dejar claro que es urgente)',['emergency','appointment','allergy','pharmacy'],0,'"It is an emergency" comunica la urgencia de la situación.'],
        ['mcq','Sientes mucha dificultad para respirar. ¿Qué dices?',['I can\'t breathe.','I have a headache.','I need a prescription.','I feel great.'],0,'"I can\'t breathe" es una frase de emergencia que requiere atención inmediata.'],
        ['translate','Traduce: "Tiene dolor en el pecho."',['He has chest pain.','He has a headache.','He needs a prescription.','He is allergic.'],0,'"Chest pain" es dolor en el pecho, un síntoma que requiere atención urgente.'],
      ],
    },
    { id:'sit_hospital_insurance', level:'B1', title:'Seguro médico y papeleo', emoji:'📋', xp:25,
      description:'Resuelve el papeleo administrativo sin complicaciones.',
      study:{ vocab:[
        ['Health insurance','Seguro médico'],
        ['Insurance card','Tarjeta del seguro'],
        ['Do you accept my insurance?','¿Aceptan mi seguro?'],
        ['Out-of-pocket','De tu propio bolsillo (sin seguro)'],
        ['Medical form','Formulario médico'],
      ]},
      ex:[
        ['mcq','Llegas a recepción y quieren saber si tienes cobertura médica. ¿Qué preguntan?',['Do you have health insurance?','Do you have a prescription?','Do you have an allergy?','Do you have an appointment?'],0,'"Do you have health insurance?" pregunta por tu cobertura médica.','📋 Estás llenando el papeleo de admisión.'],
        ['fill','"Do you accept my ___?" (para saber si tu seguro es válido ahí)',['insurance','prescription','appointment','symptom'],0,'"Do you accept my insurance?" confirma si tu seguro es válido en ese hospital.'],
        ['mcq','No tienes seguro y deberás pagar tú mismo. ¿Cómo se dice eso?',['Out-of-pocket','Insurance card','Medical form','Prescription'],0,'"Out-of-pocket" significa pagar tú mismo, sin ayuda del seguro.'],
        ['translate','Traduce: "Necesito llenar este formulario médico."',['I need to fill out this medical form.','I need to see a doctor.','I need a prescription.','I need an ambulance.'],0,'"Fill out this form" significa completar el documento con tus datos.'],
      ],
    },
    { id:'sit_hospital_followup', level:'B1', title:'Seguimiento y citas de control', emoji:'📅', xp:30,
      description:'Practica cómo organizar una cita de seguimiento.',
      study:{ grammar:[
        ['"I need to follow up on..." para dar seguimiento','Se usa para pedir una cita relacionada con un tratamiento o consulta anterior.','I need to follow up on my test results. → Necesito dar seguimiento a los resultados de mis análisis.'],
      ]},
      ex:[
        ['mcq','Tuviste una consulta la semana pasada y necesitas otra cita relacionada. ¿Qué dices?',['I need to follow up on my last visit.','I need an ambulance.','I need a painkiller.','I need my insurance card.'],0,'"Follow up on my last visit" pide continuar el seguimiento de una consulta anterior.','📅 Llamas para agendar otra cita.'],
        ['fill','"When ___ my test results be ready?" (¿cuándo estarán listos?)',['will','are','did','have'],0,'"When will my results be ready?" pregunta por la fecha en la que tendrás los resultados.'],
        ['translate','Traduce: "¿Podemos agendar una cita de control para el próximo mes?"',['Can we schedule a follow-up appointment for next month?','Can we schedule a delivery for next month?','Can we schedule a flight for next month?','Can we schedule a table for next month?'],0,'"Follow-up appointment" es una cita de control o seguimiento.'],
        ['speaking','Simula que llamas para agendar una cita de seguimiento después de una consulta anterior. (mínimo 25 palabras)',[],['follow up','appointment','next'],'Una buena respuesta pide una cita de seguimiento y propone una fecha.'],
      ],
    },
  ],

  office: [
    { id:'sit_office_vocab', level:'B1', title:'Vocabulario de oficina', emoji:'💼', xp:25,
      description:'Lo básico para tu día a día laboral.',
      study:{ vocab:[
        ['Deadline','Fecha límite'],
        ['Meeting','Reunión'],
        ['Colleague / Coworker','Compañero/a de trabajo'],
        ['Report','Informe'],
        ['Schedule','Agenda / horario'],
        ['Task','Tarea'],
      ]},
      ex:[
        ['mcq','¿Cómo se dice "fecha límite" en inglés?',['Deadline','Meeting','Schedule','Task'],0,'"Deadline" es la fecha máxima para entregar algo.','💼 Estás en tu oficina revisando pendientes.'],
        ['fill','"Let\'s schedule a ___ for tomorrow."',['meeting','deadline','report','task'],0,'"Schedule a meeting" significa organizar una reunión.'],
        ['translate','Traduce: "compañero de trabajo"',['Colleague','Deadline','Report','Task'],0,'"Colleague" (o "coworker") es alguien con quien trabajas.'],
        ['mcq','Tu jefe te pide un documento con resultados. ¿Qué palabra usa probablemente?',['Report','Deadline','Colleague','Meeting'],0,'"Report" es un informe con información o resultados.'],
        ['arrange','Ordena: [is / when / the / deadline]',['When is the deadline','Deadline is when the','Is when the deadline','The deadline is when'],0,'"When is the deadline?" pregunta por la fecha límite.'],
      ],
    },
    { id:'sit_office_phrases', level:'B1', title:'Frases para el trabajo', emoji:'💬', xp:25,
      description:'Pide ayuda, organiza reuniones y da actualizaciones.',
      study:{ vocab:[
        ['Could you help me with this?','¿Podrías ayudarme con esto?'],
        ['When is the deadline?','¿Cuándo es la fecha límite?'],
        ['Can we schedule a meeting?','¿Podemos agendar una reunión?'],
        ['I will send you the report today.','Te enviaré el informe hoy.'],
        ['Can we reschedule?','¿Podemos reagendar?'],
      ]},
      ex:[
        ['mcq','Necesitas ayuda de un compañero con una tarea. ¿Qué dices?',['Could you help me with this?','Can we reschedule?','When is the deadline?','I will send you the report.'],0,'"Could you help me with this?" pide ayuda de forma educada.','💼 Tienes una tarea complicada.'],
        ['fill','"I will ___ you the report today."',['send','have','make','do'],0,'"I will send you..." indica que enviarás algo pronto.'],
        ['mcq','Tienes un conflicto de horario con una reunión. ¿Qué preguntas?',['Can we reschedule?','Could you help me with this?','When is the deadline?','Can we schedule a meeting?'],0,'"Can we reschedule?" pide cambiar la hora de la reunión.'],
        ['translate','Traduce: "¿Podemos agendar una reunión?"',['Can we schedule a meeting?','Can we reschedule?','When is the deadline?','Could you help me with this?'],0,'"Can we schedule a meeting?" propone organizar una reunión.'],
        ['mcq','Tu jefe dice "The deadline is Friday." ¿Qué acabas de entender?',['La fecha límite es el viernes','La reunión es el viernes','El informe llegó el viernes','No hay reunión el viernes'],0,'Te está confirmando cuándo vence el plazo.'],
      ],
    },
    { id:'sit_office_dialogue', level:'B1', title:'Diálogo: pedir ayuda', emoji:'🗣️', xp:30,
      description:'Sigue una conversación laboral típica.',
      study:{ grammar:[
        ['Futuro con "will" para promesas de trabajo','Usa "will" para comprometerte a hacer algo pronto.','I will finish it by Friday. → Lo terminaré para el viernes.'],
      ]},
      ex:[
        ['mcq','Colega: "Do you have a minute? I need your help with the report." ¿Qué te pide?',['Ayuda con un informe','Ayuda con una reserva','Ayuda con una receta médica','Ayuda con un vuelo'],0,'"I need your help with the report" pide ayuda con un informe.','🎬 Diálogo — un compañero se acerca a tu escritorio.'],
        ['mcq','Tú respondes: "Sure, what do you need?" ¿Qué acabas de decir?',['Que estás dispuesto a ayudar y preguntas qué necesita','Que no puedes ayudar','Que estás en una reunión','Que necesitas el informe tú'],0,'"Sure, what do you need?" muestra disposición a ayudar.','🎬 Diálogo — aceptas ayudar.'],
        ['fill','Tu compañero dice: "___ you send it to me by tomorrow?"',['Could','Is','Have','Do'],0,'"Could you send it to me...?" pide algo de forma educada.'],
        ['translate','Traduce: "Lo terminaré para mañana."',['I will finish it by tomorrow.','I finished it yesterday.','I am finishing it now.','I have finished it.'],0,'"I will finish it by tomorrow" es una promesa a futuro con "will".'],
        ['writing','Escribe un breve intercambio (mínimo 25 palabras) donde un compañero te pide ayuda con una tarea y tú aceptas dando un plazo.',[],['help','deadline','will'],'Debe incluir pedir/dar ayuda y mencionar un plazo con "will".'],
      ],
    },
    { id:'sit_office_meetings', level:'B1', title:'Reuniones y presentaciones', emoji:'📊', xp:25,
      description:'Vocabulario para participar con confianza en una reunión.',
      study:{ vocab:[
        ['Agenda','Orden del día'],
        ['Let\'s get started.','Empecemos.'],
        ['Any questions?','¿Alguna pregunta?'],
        ['I would like to add something.','Me gustaría añadir algo.'],
        ['Action items','Tareas a realizar'],
        ['To sum up...','Para resumir...'],
      ]},
      ex:[
        ['mcq','El jefe empieza la reunión. ¿Qué frase usa probablemente?',['Let\'s get started.','Could we have the bill?','Is this table free?','Do you accept cards?'],0,'"Let\'s get started" es la forma común de iniciar una reunión.','📊 Todos se sientan en la sala de reuniones.'],
        ['fill','"I would like to ___ something to that point." (opinar sobre lo dicho)',['add','claim','declare','book'],0,'"I would like to add something" introduce tu opinión educadamente.'],
        ['mcq','La reunión termina y alguien resume los próximos pasos. ¿Qué palabra usa?',['Action items','Agenda','Dosage','Refund'],0,'"Action items" son las tareas que deben hacerse después de la reunión.'],
        ['translate','Traduce: "Para resumir, necesitamos terminar esto para el viernes."',['To sum up, we need to finish this by Friday.','To start, we need to finish this by Friday.','To sum up, we need a meeting on Friday.','To start, we need a report on Friday.'],0,'"To sum up..." se usa para cerrar con un resumen breve.'],
      ],
    },
    { id:'sit_office_email', level:'B1', title:'Correos breves de trabajo', emoji:'✉️', xp:25,
      description:'Escribe mensajes de trabajo claros y profesionales.',
      study:{ vocab:[
        ['I am writing to...','Le escribo para...'],
        ['Please find attached...','Adjunto encontrará...'],
        ['Looking forward to your reply.','Espero su respuesta.'],
        ['Best regards,','Saludos cordiales,'],
        ['As discussed,','Como comentamos,'],
      ]},
      ex:[
        ['mcq','Empiezas un correo explicando el motivo del mensaje. ¿Qué frase usas?',['I am writing to ask about the schedule.','Let\'s get started.','Could you help me with this?','Any questions?'],0,'"I am writing to..." es la forma estándar de comenzar un correo formal.','✉️ Abres un nuevo correo de trabajo.'],
        ['fill','"Please find ___ the report." (el archivo va adjunto)',['attached','included','sent','signed'],0,'"Please find attached" indica que hay un archivo adjunto en el correo.'],
        ['mcq','Terminas el correo esperando una respuesta pronto. ¿Qué frase usas?',['Looking forward to your reply.','Let\'s get started.','Any questions?','I would like to add something.'],0,'"Looking forward to your reply" cierra el correo educadamente.'],
        ['translate','Traduce: "Como comentamos ayer, adjunto el informe."',['As discussed yesterday, please find the report attached.','As discussed yesterday, let\'s get started.','As discussed yesterday, any questions?','As discussed yesterday, I need a deadline.'],0,'"As discussed yesterday" conecta el correo con una conversación previa.'],
      ],
    },
    { id:'sit_office_conflict', level:'B1', title:'Desacuerdos profesionales', emoji:'⚖️', xp:30,
      description:'Expresa una opinión diferente sin sonar brusco.',
      study:{ vocab:[
        ['I see your point, but...','Entiendo tu punto, pero...'],
        ['I am not sure I agree.','No estoy seguro de estar de acuerdo.'],
        ['Could we find a middle ground?','¿Podríamos llegar a un punto medio?'],
        ['Let\'s agree to disagree.','Aceptemos que pensamos distinto.'],
      ]},
      ex:[
        ['mcq','No estás de acuerdo con la idea de un compañero, pero quieres ser respetuoso. ¿Qué dices?',['I see your point, but I have a different idea.','That is a terrible idea.','I am always right.','Let\'s get started.'],0,'"I see your point, but..." muestra respeto antes de dar tu opinión.','⚖️ Estás en una reunión con opiniones divididas.'],
        ['fill','"Could we find a ___ ground?" (una solución intermedia)',['middle','high','low','common'],0,'"Middle ground" es un punto intermedio que satisface a ambas partes.'],
        ['translate','Traduce: "No estoy seguro de estar de acuerdo con ese plan."',['I am not sure I agree with that plan.','I am not sure I understand that plan.','I am not sure I like that report.','I am not sure I need that meeting.'],0,'"I am not sure I agree" expresa desacuerdo de forma suave.'],
        ['speaking','Simula que estás en desacuerdo con la idea de un compañero, pero lo expresas con respeto y propones una alternativa. (mínimo 25 palabras)',[],['I see your point','but','middle ground'],'Una buena respuesta reconoce la otra opinión antes de dar la propia.'],
      ],
    },
    { id:'sit_office_timeoff', level:'B1', title:'Pedir tiempo libre', emoji:'🏖️', xp:25,
      description:'Solicita días libres o ausencias de forma profesional.',
      study:{ vocab:[
        ['Time off','Tiempo libre'],
        ['Sick day','Día por enfermedad'],
        ['Vacation days','Días de vacaciones'],
        ['Could I take next Friday off?','¿Podría tomar libre el próximo viernes?'],
        ['I am not feeling well.','No me siento bien.'],
      ]},
      ex:[
        ['mcq','Quieres pedir un día libre la próxima semana. ¿Qué preguntas a tu jefe?',['Could I take next Friday off?','Let\'s get started.','I see your point.','Any questions?'],0,'"Could I take next Friday off?" pide un día específico libre.','🏖️ Piensas pedir un día libre.'],
        ['fill','"I am not feeling well, I need a ___ day." (por enfermedad)',['sick','vacation','work','meeting'],0,'"Sick day" es un día libre por enfermedad.'],
        ['mcq','Quieres saber cuántos días de vacaciones te quedan este año. ¿Qué preguntas?',['How many vacation days do I have left?','How many sick days do I have left?','How many action items do I have?','How many meetings do I have?'],0,'"Vacation days" son los días de descanso pagado disponibles.'],
        ['translate','Traduce: "No me siento bien, necesito tomar el día libre."',['I am not feeling well, I need to take the day off.','I am not feeling well, I need a meeting.','I am not feeling well, I need a raise.','I am not feeling well, I need a report.'],0,'"Take the day off" significa no ir a trabajar ese día.'],
      ],
    },
  ],

  party: [
    { id:'sit_party_vocab', level:'A2', title:'Vocabulario de la fiesta', emoji:'🎉', xp:25,
      description:'Para romper el hielo con confianza.',
      study:{ vocab:[
        ['Host','Anfitrión/a'],
        ['Guest','Invitado/a'],
        ['Small talk','Conversación ligera'],
        ['To introduce (someone)','Presentar (a alguien)'],
        ['Toast','Brindis'],
        ['Get-together','Reunión informal'],
      ]},
      ex:[
        ['mcq','¿Cómo se dice "anfitrión" en inglés?',['Host','Guest','Toast','Small talk'],0,'"Host" es la persona que organiza la fiesta.','🎉 Llegas a una fiesta y no conoces a nadie.'],
        ['fill','"Let\'s make a ___ to the birthday girl!"',['toast','host','guest','get-together'],0,'"Make a toast" significa brindar por alguien.'],
        ['translate','Traduce: "presentar a alguien"',['To introduce someone','To toast someone','To host someone','To invite someone'],0,'"To introduce someone" es cuando presentas a dos personas.'],
        ['mcq','Quieres hablar de temas ligeros para romper el hielo. ¿Cómo se llama eso?',['Small talk','Toast','Host','Guest'],0,'"Small talk" es la conversación informal típica al conocer gente.'],
        ['arrange','Ordena: [know / how / you / host / the / do]',['How do you know the host','Do you know how the host','The host do you know how','How the host do you know'],0,'"How do you know the host?" es una pregunta clásica para romper el hielo.'],
      ],
    },
    { id:'sit_party_phrases', level:'A2', title:'Frases para socializar', emoji:'💬', xp:25,
      description:'De saludar a despedirte con estilo.',
      study:{ vocab:[
        ['How do you know the host?','¿Cómo conoces al anfitrión?'],
        ['What do you like to do in your free time?','¿Qué te gusta hacer en tu tiempo libre?'],
        ['That sounds interesting!','¡Eso suena interesante!'],
        ['Can I introduce you to...?','¿Te puedo presentar a...?'],
        ['It was lovely talking to you.','Fue un placer hablar contigo.'],
      ]},
      ex:[
        ['mcq','Conoces a alguien nuevo en la fiesta. ¿Qué preguntas para empezar?',['How do you know the host?','It was lovely talking to you.','Can I introduce you to...?','That sounds interesting!'],0,'Es una pregunta natural para romper el hielo en una fiesta.','🎉 Estás junto a alguien que no conoces.'],
        ['fill','"What do you ___ to do in your free time?"',['like','make','have','go'],0,'"What do you like to do...?" pregunta por sus intereses o hobbies.'],
        ['mcq','Alguien te cuenta algo interesante. ¿Cómo reaccionas amablemente?',['That sounds interesting!','It was lovely talking to you.','How do you know the host?','Can I introduce you to...?'],0,'"That sounds interesting!" muestra interés genuino en lo que cuentan.'],
        ['translate','Traduce: "Fue un placer hablar contigo."',['It was lovely talking to you.','That sounds interesting.','How do you know the host?','Can I introduce you to my friend?'],0,'Es la despedida educada típica al terminar una charla en una fiesta.'],
        ['mcq','Quieres presentar a dos amigos entre sí. ¿Qué dices?',['Can I introduce you to my friend?','That sounds interesting!','How do you know the host?','It was lovely talking to you.'],0,'"Can I introduce you to...?" es la forma de presentar a alguien.'],
      ],
    },
    { id:'sit_party_dialogue', level:'A2', title:'Diálogo: conociendo gente', emoji:'🗣️', xp:30,
      description:'Sigue una charla casual de principio a fin.',
      study:{ grammar:[
        ['Preguntas abiertas para conversar','Las preguntas con "What/How" invitan a respuestas más largas que las de sí/no — ideales para el small talk.','What do you do for a living? → ¿A qué te dedicas?'],
      ]},
      ex:[
        ['mcq','Alguien te dice: "Hi! I don\'t think we\'ve met. I\'m Sam." ¿Qué haces primero?',['Te presentas también','Le pides la cuenta','Le preguntas la fecha límite','Le preguntas si es una emergencia'],0,'Cuando alguien se presenta, lo natural es presentarte también.','🎬 Diálogo — alguien se te acerca en la fiesta.'],
        ['mcq','Sam pregunta: "So, how do you know Maria?" (la anfitriona). ¿Qué te está preguntando?',['Cómo conoces a la anfitriona','Dónde vives','Qué estudias','A qué hora es la fiesta'],0,'Te pregunta la conexión que tienes con la anfitriona de la fiesta.','🎬 Diálogo — sigue la conversación.'],
        ['fill','Quieres saber más de sus intereses: "What do you like ___ in your free time?"',['to do','doing','do','done'],0,'"What do you like to do...?" usa "to do" (infinitivo) después de "like".'],
        ['translate','Traduce: "No creo que nos hayamos conocido antes."',['I don\'t think we\'ve met before.','I don\'t think this is fresh.','I don\'t think it is included.','I don\'t think you are allergic.'],0,'Frase típica para presentarte a alguien nuevo en una fiesta.'],
        ['speaking','Simula que conoces a alguien nuevo en una fiesta: preséntate, pregunta cómo conoce al anfitrión y despídete con cortesía. (mínimo 25 palabras)',[],['host','free time','lovely'],'Una buena respuesta incluye presentación, una pregunta sobre el anfitrión y una despedida cortés.'],
      ],
    },
    { id:'sit_party_invite', level:'A2', title:'Invitar y ser invitado', emoji:'💌', xp:25,
      description:'Cómo invitar a alguien o responder a una invitación.',
      study:{ vocab:[
        ['Would you like to come?','¿Te gustaría venir?'],
        ['I would love to!','¡Me encantaría!'],
        ['I am afraid I can\'t make it.','Me temo que no podré ir.'],
        ['What time should I arrive?','¿A qué hora debo llegar?'],
        ['Can I bring anything?','¿Puedo llevar algo?'],
      ]},
      ex:[
        ['mcq','Invitas a un amigo a una fiesta. ¿Qué le preguntas?',['Would you like to come?','That sounds interesting!','How do you know the host?','It was lovely talking to you.'],0,'"Would you like to come?" es la forma directa de invitar a alguien.','💌 Escribes un mensaje a un amigo.'],
        ['fill','Aceptas encantado la invitación: "I would ___ to!"',['love','like','want','need'],0,'"I would love to!" muestra entusiasmo al aceptar.'],
        ['mcq','No puedes ir a la fiesta y quieres decirlo con cortesía. ¿Qué dices?',['I am afraid I can\'t make it.','I would love to!','What time should I arrive?','Can I bring anything?'],0,'"I am afraid I can\'t make it" rechaza la invitación educadamente.'],
        ['translate','Traduce: "¿Puedo llevar algo a la fiesta?"',['Can I bring anything to the party?','Can I invite someone to the party?','What time should I arrive at the party?','Would you like to come to the party?'],0,'"Can I bring anything?" ofrece llevar algo (comida, bebida, etc.).'],
      ],
    },
    { id:'sit_party_food', level:'A2', title:'Comida y bebida en la fiesta', emoji:'🍹', xp:25,
      description:'Habla de lo que se sirve y pide lo que quieras.',
      study:{ vocab:[
        ['Help yourself!','¡Sírvete tú mismo!'],
        ['This is delicious, what is it?','Esto está delicioso, ¿qué es?'],
        ['I will have a soda, please.','Tomaré un refresco, por favor.'],
        ['Are you hungry?','¿Tienes hambre?'],
        ['No, thank you, I am full.','No, gracias, estoy lleno.'],
      ]},
      ex:[
        ['mcq','El anfitrión te ofrece comida y bebida libremente. ¿Qué dice?',['Help yourself!','I am full.','Would you like to come?','What time should I arrive?'],0,'"Help yourself!" invita a servirse libremente la comida o bebida.','🍹 Hay una mesa llena de comida.'],
        ['fill','Alguien te ofrece más comida, pero ya comiste suficiente: "No, thank you, I am ___."',['full','hungry','thirsty','tired'],0,'"I am full" significa que ya no puedes comer más.'],
        ['mcq','No quieres alcohol, prefieres algo sin. ¿Qué pides?',['I will have a soda, please.','I will have a bill, please.','I will have a receipt, please.','I will have a discount, please.'],0,'"I will have a soda" pide una bebida sin alcohol.'],
        ['translate','Traduce: "Esto está delicioso, ¿qué es?"',['This is delicious, what is it?','This is expensive, what is it?','This is spicy, what is it?','This is cold, what is it?'],0,'Un buen cumplido curioso sobre un platillo que probaste.'],
      ],
    },
    { id:'sit_party_awkward', level:'B1', title:'Situaciones incómodas', emoji:'😅', xp:30,
      description:'Cómo salir con elegancia de momentos incómodos.',
      study:{ vocab:[
        ['I am sorry, I did not catch your name.','Perdón, no entendí tu nombre.'],
        ['If you\'ll excuse me...','Si me disculpas...'],
        ['I should probably mingle a bit.','Debería socializar un poco más.'],
        ['I am not sure about that, actually.','La verdad, no estoy tan seguro de eso.'],
      ]},
      ex:[
        ['mcq','No recuerdas el nombre de alguien que te habla. ¿Qué dices con cortesía?',['I am sorry, I did not catch your name.','That sounds interesting!','Help yourself!','Can I bring anything?'],0,'"I did not catch your name" pide el nombre sin ser incómodo.','😅 Alguien te habla, pero no recuerdas su nombre.'],
        ['fill','Quieres alejarte educadamente de una conversación: "If you\'ll ___ me..."',['excuse','forgive','help','invite'],0,'"If you\'ll excuse me..." es la forma cortés de retirarte de una charla.'],
        ['translate','Traduce: "No estoy tan seguro de eso, la verdad."',['I am not sure about that, actually.','I am not hungry, actually.','I am not invited, actually.','I am not late, actually.'],0,'Frase útil para mostrar desacuerdo suave sin ser brusco.'],
        ['speaking','Simula una situación incómoda en una fiesta (no recuerdas un nombre, o quieres cambiar de conversación) y resuélvela con cortesía. (mínimo 25 palabras)',[],['excuse me','sorry','actually'],'Una buena respuesta maneja la situación con cortesía y naturalidad.'],
      ],
    },
    { id:'sit_party_goodbye', level:'A2', title:'Despedidas y planes futuros', emoji:'👋', xp:25,
      description:'Termina la noche dejando una buena impresión.',
      study:{ vocab:[
        ['I should get going.','Debería irme.'],
        ['Thank you for having me.','Gracias por invitarme.'],
        ['We should hang out again sometime.','Deberíamos volver a vernos.'],
        ['Let\'s exchange numbers.','Intercambiemos números.'],
        ['Take care!','¡Cuídate!'],
      ]},
      ex:[
        ['mcq','Es tarde y quieres irte de la fiesta. ¿Qué dices?',['I should get going.','I would love to!','Help yourself!','Are you hungry?'],0,'"I should get going" anuncia que te vas de forma natural.','👋 Ya es tarde y quieres despedirte.'],
        ['fill','Agradeces al anfitrión antes de irte: "Thank you for ___ me."',['having','inviting','bringing','helping'],0,'"Thank you for having me" agradece la invitación a la fiesta.'],
        ['mcq','Conociste a alguien interesante y quieres seguir en contacto. ¿Qué propones?',['Let\'s exchange numbers.','I should get going.','Take care!','Help yourself!'],0,'"Let\'s exchange numbers" propone mantener el contacto después.'],
        ['translate','Traduce: "Deberíamos volver a vernos pronto."',['We should hang out again sometime.','We should get going sometime.','We should exchange numbers sometime.','We should help ourselves sometime.'],0,'Expresa interés en verse de nuevo en el futuro.'],
      ],
    },
  ],

  university: [
    { id:'sit_university_vocab', level:'B1', title:'Vocabulario universitario', emoji:'🎓', xp:25,
      description:'Términos clave para trámites y clases.',
      study:{ vocab:[
        ['Enrollment','Matrícula / inscripción'],
        ['Course','Curso / asignatura'],
        ['Professor','Profesor/a'],
        ['Assignment / deadline','Tarea / fecha límite'],
        ['Campus','Campus'],
        ['Tuition','Matrícula (costo)'],
      ]},
      ex:[
        ['mcq','¿Cómo se dice "matrícula" (inscripción) en inglés?',['Enrollment','Campus','Tuition','Course'],0,'"Enrollment" es el proceso de inscribirte a un curso o programa.','🎓 Estás en la oficina de administración de la universidad.'],
        ['fill','"When does ___ close?" (para inscribirte a tiempo)',['enrollment','tuition','campus','course'],0,'"When does enrollment close?" pregunta la fecha límite para inscribirte.'],
        ['translate','Traduce: "profesor"',['Professor','Course','Campus','Tuition'],0,'"Professor" es quien imparte las clases universitarias.'],
        ['mcq','Preguntas cuánto cuesta estudiar allí. ¿Qué palabra usas?',['Tuition','Campus','Enrollment','Assignment'],0,'"Tuition" se refiere al costo de la matrícula/estudios.'],
        ['arrange','Ordena: [this / course / about / information / like / I / would]',['I would like information about this course','Would I like information about this course','Information I would like about this course','About this course I would like information'],0,'"I would like information about this course" pide información de forma educada.'],
      ],
    },
    { id:'sit_university_phrases', level:'B1', title:'Frases para trámites', emoji:'💬', xp:25,
      description:'Pregunta por cursos, requisitos y plazos.',
      study:{ vocab:[
        ['I would like information about this course.','Quisiera información sobre este curso.'],
        ['What are the entry requirements?','¿Cuáles son los requisitos de admisión?'],
        ['When does enrollment close?','¿Cuándo cierra la inscripción?'],
        ['Could you explain the schedule?','¿Podría explicarme el horario?'],
        ['Is there financial aid?','¿Hay ayuda financiera disponible?'],
      ]},
      ex:[
        ['mcq','Llegas a la oficina de admisiones interesado en un curso. ¿Qué dices?',['I would like information about this course.','Is there financial aid?','When does enrollment close?','Could you explain the schedule?'],0,'Es la forma natural de iniciar la consulta sobre un curso.','🎓 Entras a la oficina de admisiones.'],
        ['fill','"What are the entry ___?"',['requirements','deadlines','courses','campuses'],0,'"Entry requirements" son los requisitos para ser admitido.'],
        ['mcq','No tienes suficiente dinero para pagar todo. ¿Qué preguntas?',['Is there financial aid?','What are the entry requirements?','Could you explain the schedule?','When does enrollment close?'],0,'"Is there financial aid?" pregunta por becas o ayudas económicas.'],
        ['translate','Traduce: "¿Cuándo cierra la inscripción?"',['When does enrollment close?','What are the entry requirements?','Is there financial aid?','Could you explain the schedule?'],0,'"When does enrollment close?" pregunta por el plazo límite de inscripción.'],
        ['mcq','El administrativo dice: "Enrollment closes on Friday." ¿Qué acabas de entender?',['El plazo de inscripción termina el viernes','El curso empieza el viernes','La beca se paga el viernes','El profesor llega el viernes'],0,'"Enrollment closes on Friday" indica la fecha límite de inscripción.'],
      ],
    },
    { id:'sit_university_dialogue', level:'B1', title:'Diálogo: en administración', emoji:'🗣️', xp:30,
      description:'Sigue una consulta académica completa.',
      study:{ grammar:[
        ['Preguntas indirectas con "Could you explain...?"','Suena más formal y educado que una pregunta directa — ideal en trámites.','Could you explain how the payment works? → ¿Podría explicarme cómo funciona el pago?'],
      ]},
      ex:[
        ['mcq','Administrativo: "How can I help you today?" ¿Qué te está preguntando?',['En qué te puede ayudar','Cuál es tu curso favorito','Dónde vives','Cuánto dinero tienes'],0,'Es una pregunta abierta para saber qué necesitas.','🎬 Diálogo — llegas a la ventanilla de administración.'],
        ['mcq','Tú: "I would like information about the English course." Administrativo: "Sure, it starts in September." ¿Qué acabas de entender?',['Cuándo empieza el curso','Cuánto cuesta el curso','Quién es el profesor','Dónde está el campus'],0,'"It starts in September" indica la fecha de inicio del curso.','🎬 Diálogo — pides información del curso.'],
        ['fill','Preguntas por el costo: "___ is the tuition for this course?"',['How much','How many','How often','How long'],0,'"How much is the tuition?" pregunta por el precio de la matrícula.'],
        ['translate','Traduce: "¿Podría explicarme el horario de clases?"',['Could you explain the class schedule?','Could you explain the entry requirements?','Is there financial aid?','When does enrollment close?'],0,'"Could you explain...?" pide una explicación de forma educada.'],
        ['writing','Escribe un breve diálogo (mínimo 25 palabras) donde pides información de un curso, preguntas los requisitos y el plazo de inscripción.',[],['course','requirements','enrollment'],'Debe incluir pedir información del curso, preguntar requisitos y el plazo de inscripción.'],
      ],
    },
    { id:'sit_university_library', level:'A2', title:'La biblioteca', emoji:'📚', xp:25,
      description:'Encuentra recursos y pide ayuda en la biblioteca.',
      study:{ vocab:[
        ['Library card','Carné de la biblioteca'],
        ['Due date','Fecha de devolución'],
        ['Renew a book','Renovar un libro'],
        ['Study room','Sala de estudio'],
        ['Return this book','Devolver este libro'],
      ]},
      ex:[
        ['mcq','Quieres sacar un libro prestado por primera vez. ¿Qué necesitas?',['A library card','A boarding pass','A receipt','A prescription'],0,'"Library card" es el carné necesario para prestar libros.','📚 Entras a la biblioteca del campus.'],
        ['fill','"When is the ___ date for this book?" (fecha límite de devolución)',['due','check-in','enrollment','delivery'],0,'"Due date" es la fecha límite para devolver el libro.'],
        ['mcq','Necesitas más tiempo con un libro que ya prestaste. ¿Qué pides?',['Could I renew this book?','Could I return this book?','Could I buy this book?','Could I copy this book?'],0,'"Renew" significa extender el plazo de préstamo de un libro.'],
        ['translate','Traduce: "¿Hay una sala de estudio disponible?"',['Is there a study room available?','Is there a library card available?','Is there a due date available?','Is there a course available?'],0,'"Study room" es un espacio para estudiar, a veces reservable.'],
      ],
    },
    { id:'sit_university_group', level:'B1', title:'Trabajo en grupo', emoji:'👥', xp:25,
      description:'Organiza tareas y comunícate con tu equipo.',
      study:{ vocab:[
        ['Let\'s divide the work.','Dividamos el trabajo.'],
        ['Who wants to present?','¿Quién quiere presentar?'],
        ['Can we meet tomorrow?','¿Podemos reunirnos mañana?'],
        ['I will handle this part.','Yo me encargo de esta parte.'],
        ['Deadline','Fecha límite'],
      ]},
      ex:[
        ['mcq','Tu grupo tiene un proyecto grande y necesitan repartirse el trabajo. ¿Qué propones?',['Let\'s divide the work.','Let\'s renew this book.','Let\'s check the due date.','Let\'s exchange numbers.'],0,'"Let\'s divide the work" propone repartir las tareas entre el equipo.','👥 Tu grupo se reúne para planear el proyecto.'],
        ['fill','Te ofreces a hacer una parte específica: "I will ___ this part."',['handle','renew','declare','claim'],0,'"I will handle this part" significa que te encargarás de esa sección.'],
        ['mcq','Necesitan coordinar un horario para reunirse de nuevo. ¿Qué preguntas?',['Can we meet tomorrow?','Who wants to present?','Is there a study room?','What is the due date?'],0,'"Can we meet tomorrow?" propone coordinar la próxima reunión.'],
        ['translate','Traduce: "¿Quién quiere presentar el proyecto?"',['Who wants to present the project?','Who wants to renew the project?','Who wants to divide the project?','Who wants to declare the project?'],0,'Pregunta quién se encargará de la presentación final.'],
      ],
    },
    { id:'sit_university_professor', level:'B1', title:'Hablar con el profesor', emoji:'🎓', xp:30,
      description:'Resuelve dudas académicas con confianza.',
      study:{ vocab:[
        ['Office hours','Horario de atención'],
        ['I have a question about...','Tengo una duda sobre...'],
        ['Could you explain this again?','¿Podría explicar esto de nuevo?'],
        ['I am struggling with...','Me está costando trabajo...'],
        ['Extension','Extensión de plazo'],
      ]},
      ex:[
        ['mcq','No entendiste un tema y quieres preguntarle al profesor. ¿Qué dices?',['I have a question about the last class.','Let\'s divide the work.','Can we meet tomorrow?','Who wants to present?'],0,'"I have a question about..." introduce tu duda claramente.','🎓 Vas a la oficina del profesor en su horario de atención.'],
        ['fill','"I am ___ with this topic, could you help me?" (te está costando)',['struggling','renewing','presenting','dividing'],0,'"Struggling with" significa que algo te está costando entender.'],
        ['mcq','Necesitas más tiempo para entregar una tarea. ¿Qué pides al profesor?',['Could I have an extension?','Could I have a library card?','Could I have a study room?','Could I have a group?'],0,'"Extension" es tiempo adicional para entregar un trabajo.'],
        ['translate','Traduce: "¿Podría explicar esto de nuevo, por favor?"',['Could you explain this again, please?','Could you renew this again, please?','Could you present this again, please?','Could you divide this again, please?'],0,'Pide amablemente que repitan una explicación.'],
      ],
    },
    { id:'sit_university_campus', level:'A2', title:'Vida en el campus', emoji:'🏫', xp:25,
      description:'Actividades y espacios fuera del salón de clase.',
      study:{ vocab:[
        ['Student club','Club estudiantil'],
        ['Cafeteria','Cafetería'],
        ['Dorm / Dormitory','Residencia estudiantil'],
        ['Campus map','Mapa del campus'],
        ['Where is the main building?','¿Dónde está el edificio principal?'],
      ]},
      ex:[
        ['mcq','Es tu primer día y no conoces el campus. ¿Qué pides?',['Could I have a campus map?','Could I have a library card?','Could I have an extension?','Could I have office hours?'],0,'"Campus map" te ayuda a orientarte en tu primer día.','🏫 Es tu primer día en la universidad.'],
        ['fill','Buscas dónde comer entre clases: "Where is the ___?" (para comer)',['cafeteria','dorm','club','office'],0,'"Cafeteria" es el lugar donde los estudiantes comen en el campus.'],
        ['mcq','Quieres unirte a una actividad extracurricular. ¿Qué buscas?',['A student club','A dorm','A campus map','Office hours'],0,'"Student club" es un grupo de actividades extracurriculares.'],
        ['translate','Traduce: "¿Dónde está el edificio principal?"',['Where is the main building?','Where is the cafeteria?','Where is my dorm?','Where is the library?'],0,'Pregunta por la ubicación del edificio principal del campus.'],
      ],
    },
  ],

};

/* Devuelve el banco de lecciones (ya normalizado con buildLessons) para una
   situación concreta, en el idioma que el usuario está aprendiendo. Si no
   hay contenido para ese idioma todavía, devuelve un array vacío — la UI
   muestra un estado vacío amistoso, igual que hace renderLessons() con los
   idiomas sin banco en js/lessons-data/. */
const _situationLessonCache = {};
function getSituationLessons(situationKey, langCode){
  const code = (langCode || (typeof state!=='undefined' && state.lang && state.lang.code) || 'EN').toUpperCase();
  const cacheKey = `${code}:${situationKey}`;
  if(!_situationLessonCache[cacheKey]){
    const raw = (window.SITUATION_LESSON_BANKS[code] && window.SITUATION_LESSON_BANKS[code][situationKey]) || [];
    _situationLessonCache[cacheKey] = (typeof buildLessons==='function') ? buildLessons(raw) : raw;
  }
  return _situationLessonCache[cacheKey];
}

// Todas las lecciones de TODAS las situaciones para el idioma activo, en un
// único array plano — es lo que necesita LessonEngine.start() para buscar
// por id sin importar de qué situación viene (ver el cambio en lessons.js).
function getAllSituationLessonsFlat(langCode){
  const code = (langCode || (typeof state!=='undefined' && state.lang && state.lang.code) || 'EN').toUpperCase();
  return SITUATIONS.flatMap(s => getSituationLessons(s.key, code));
}
