// Ronda 8 (2.ª pasada): segmentos y opciones en inglés -> español
module.exports.OPT=[
"¿Cómo te llamas?","¿De dónde eres?","¿Cuántos años tienes?","¿Dónde vives?",
"Rojo","Azul","Verde","Amarillo",
"Cocina","Dormitorio","Baño","Jardín",
"La cuenta, por favor","El menú, por favor","La mesa, por favor","El agua, por favor",
"Desayunar","Almorzar","Cenar","Dormir",
"Probarse ropa","Comprar ropa","Lavar ropa","Doblar ropa",
"Los altavoces inteligentes se pueden controlar por texto.","Las cámaras de seguridad se pueden controlar por voz.","Los altavoces inteligentes se pueden controlar por voz.","Los termostatos se pueden controlar por texto.",
"Estoy adjuntando el correo solicitado.","Estoy adjuntando el informe solicitado.","Estoy llamando por el informe solicitado.","Estoy posponiendo el informe solicitado.",
"Corte la masa durante diez minutos.","Fría la masa durante diez minutos.","Deje reposar la masa durante diez minutos.","Hierva la masa durante diez minutos.",
"Una sugerencia sería empezar por las conclusiones.","Un problema sería empezar por las conclusiones.","Una crítica sería empezar por las conclusiones.","Una sugerencia sería terminar con las conclusiones.",
"sin duda","por lo tanto","quizás","apenas... cuando...",
"Intento no depender demasiado de mi teléfono.","Intento depender demasiado de mi teléfono.","No intento depender de mi teléfono.","Dependo demasiado de mi teléfono.",
"Según el autor, los resultados no son concluyentes.","Según el autor, los resultados son concluyentes.","Según los resultados, el autor no es concluyente.","Según los resultados, el autor es poco fiable.",
"Algunos trabajos se automatizarán, pero también se crearán otros nuevos.","Algunos trabajos se automatizarán y no se creará ninguno nuevo.","Todos los trabajos se automatizarán, pero se crearán otros nuevos.","Algunos trabajos se crearán, pero otros nuevos se automatizarán.",
"¿Está incluida la propina?","¿Hay que añadir la propina?","¿Dónde se paga la propina?","¿Cuánto es la propina?",
"Pedir ayuda no es una señal de debilidad.","Pedir ayuda no es una señal de inteligencia.","Ofrecer ayuda no es una señal de debilidad.","No pedir ayuda es una señal de debilidad.",
"El contrato está sujeto a los términos y condiciones descritos en el Anexo A.","El contrato anula los términos y condiciones descritos en el Anexo A.","El contrato está sujeto a los términos y condiciones del Anexo B.","Los términos del Anexo A están sujetos a lo que diga el contrato.",
"La falta de fiabilidad del narrador obliga al lector a cuestionar cada afirmación.","La fiabilidad del narrador permite al lector aceptar cada afirmación.","El narrador obliga al lector a cuestionar al autor.","El lector obliga al narrador a cuestionar cada afirmación.",
"Tiene el pelo largo y usa lentes.","Tiene el pelo corto y usa lentes.","Tiene el pelo largo y no usa lentes.","Tiene el pelo largo y lleva sombrero.",
"Prefiero aprender a mi propio ritmo.","Prefiero aprender al ritmo de los demás.","Prefiero no aprender a mi propio ritmo.","Prefiero que me enseñen a su propio ritmo.",
"Esto es un acto de habla indirecto: su forma literal no coincide con su función real.","Esto es un acto de habla directo: su forma literal coincide con su función real.","Es un acto de habla que no tiene forma literal ni función.","Esto es un acto de habla indirecto: su función literal no coincide con su forma real.",
"Esta puesta en escena me pareció sobrevalorada.","Esta actuación me dejó una impresión duradera.","Este estilo me dejó una impresión duradera.","Esta actuación me dejó indiferente.",
"Una lengua viva evoluciona con el uso, nos guste o no.","Una lengua muerta evoluciona con el uso, nos guste o no.","Una lengua viva evoluciona con el uso, aunque no cambie.","Una lengua viva evoluciona sin el uso, nos guste o no."
];
module.exports.SEG={
"black":"negro","she is 25 years old":"ella tiene 25 años","we are french":"somos franceses","mother":"madre","my brother":"mi hermano","grandparents":"abuelos","i would like":"quisiera","waiter":"camarero","every day":"todos los días","more...than":"más... que","it's cold":"hace frío","it snows":"nieva","it's raining right now.":"está lloviendo ahora mismo.","sunny":"soleado","last week":"la semana pasada","i'm wearing a red dress.":"llevo puesto un vestido rojo.","cold":"frío","rainy":"lluvioso","space station":"estación espacial","free will":"libre albedrío","memory card":"tarjeta de memoria","hiking trail":"sendero","scissors":"tijeras","sheet music":"partitura","without rehabilitation, recidivism might increase.":"sin rehabilitación, la reincidencia podría aumentar.","speech act":"acto de habla","ambiguity":"ambigüedad","birth certificate":"certificado de nacimiento","affordable housing":"vivienda asequible","black belt":"cinturón negro","balance":"equilibrio","tectonic plate":"placa tectónica","antenna":"antena","zodiac sign":"signo del zodiaco","free fall":"caída libre","licensing agreement":"contrato de licencia","mri scan":"resonancia magnética","between":"entre","i love":"me encanta","next week":"la próxima semana","as expensive as":"tan caro como","anna's book":"el libro de Anna","ana's book":"el libro de Ana","she has a car":"ella tiene un auto","we are german":"somos alemanes","we are italian":"somos italianos","she is tired today, temporal":"hoy ella está cansada, temporal",
"by no means":"de ninguna manera","turn right":"gire a la derecha","to pull someone's leg":"tomarle el pelo a alguien","single-use products":"productos desechables","commit without fully committing":"comprometerse sin comprometerse del todo","has long hair":"tiene el pelo largo","wears glasses":"usa lentes","indirect speech act":"acto de habla indirecto","literal form":"forma literal","intended function":"función pretendida","controlled by voice":"controlado por voz","i'm attaching":"estoy adjuntando","the requested report":"el informe solicitado","i'm wearing":"llevo puesto","a red dress":"un vestido rojo","left a lasting impression":"dejó una impresión duradera","one suggestion would be to":"una sugerencia sería","increasingly common":"cada vez más frecuente","decision-making":"toma de decisiones","not yet":"todavía no","might increase":"podría aumentar","enough money":"suficiente dinero","try on":"probarse","to have just done":"acabar de hacer algo","no sooner...than...":"apenas... cuando...","by herself":"ella sola","to depend on":"depender de","i try not to depend on my phone too much.":"intento no depender demasiado de mi teléfono.","according to the author":"según el autor","inconclusive":"no concluyente","some jobs will be automated, but new ones will also be created":"algunos trabajos se automatizarán, pero también se crearán otros nuevos","is the tip included?":"¿está incluida la propina?","asking for help is not a sign of weakness.":"pedir ayuda no es una señal de debilidad.","is subject to":"está sujeto a","described in appendix a":"descrito en el Anexo A","to learn at my own pace":"aprender a mi propio ritmo","this performance left a lasting impression on me":"esta actuación me dejó una impresión duradera","whether we like it or not":"nos guste o no","used to":"solía","not only...but also...":"no solo... sino también...","if":"si"
};
module.exports.GLOSS={
"kitchen":"cocina","bedroom":"dormitorio","bathroom":"baño","garden":"jardín","my brother":"mi hermano","the bill, please":"la cuenta, por favor","i would like a glass of water":"quisiera un vaso de agua","to have breakfast":"desayunar","to have lunch":"almorzar","to have dinner":"cenar","every day":"todos los días","one day":"un día","this is exactly my size":"esta es exactamente mi talla","this is my size":"esta es mi talla","it's very hot today":"hoy hace mucho calor","it's very cold today":"hoy hace mucho frío","it's cold":"hace frío","it's hot":"hace calor","mother":"madre","father":"padre","sister":"hermana","grandmother":"abuela","grandparents":"abuelos","parents":"padres","aunt and uncle":"tíos","i have three siblings":"tengo tres hermanos","i have three brothers":"tengo tres hermanos","i am very happy":"estoy muy feliz","to try on":"probarse","red":"rojo","blue":"azul","green":"verde","yellow":"amarillo","white":"blanco","black":"negro"
};
