// Ronda 9: notas de study.grammar de FR/DE/IT/PT que comparaban con el inglés -> comparación con el español
// Clave: índice en /tmp/gram87.json (orden FR, DE, IT, PT). T = título (solo si cambia), D = descripción nueva.
module.exports={
0:{D:`Avec les métiers, "être" ne prend pas d'article indéfini, comme en espagnol (“Soy profesor”).`},
1:{D:`“Pouvoir” + infinitivo expresa posibilidad en registro formal/legal, similar a «podría» (condicional de «poder») o «puede que» en español.`},
2:{D:`“À peine... que” expresa que una acción ocurrió inmediatamente después de otra, equivalente a «apenas... cuando» en español; en registro muy formal puede invertir sujeto-verbo.`},
3:{D:`“Combien de” no varía y se usa tanto con sustantivos contables como incontables para preguntar cantidad, a diferencia del español («cuánto/cuánta/cuántos/cuántas»).`},
4:{D:`“Pourvu que” y “à condition que” + subjonctif expresan una condición necesaria, equivalentes a «siempre que» o «con tal de que» en español.`},
5:{D:`“Sans” + sustantivo y “n'était (le fait que)” expresan una condición hipotética formal, equivalentes a «de no ser por» o «si no fuera por» en español.`},
6:{D:`“Ça fait” + tiempo + “que” + presente expresa una acción que empezó en el pasado y continúa, equivalente a «hace... que» o «llevar + gerundio» en español.`},
7:{D:`“Peu imaginaient” o “personne ne s'attendait à” al inicio enfatizan que algo fue una sorpresa total, equivalente a «pocos se imaginaban» o «nadie esperaba» en español.`},
8:{D:`“En plus de” + infinitivo o sustantivo y “ainsi que” añaden información extra, similares a «además de» en español.`},
9:{D:`“Dans la mesure où” expresa una limitación o condición parcial, típica del registro académico/formal, equivalente a «en la medida en que» en español.`},
10:{D:`A diferencia del español («su/sus»), en francés “son/sa/ses” concuerda también en género con el sustantivo que sigue, no con el género de la persona que posee.`},
11:{D:`Como el «hay» español, “il y a” es invariable: no cambia con el número del sustantivo.`},
12:{D:`Como en español («me gusta leer»), en francés el verbo que sigue a “aimer”, “adorer” o “détester” va en infinitivo.`},
13:{D:`El francés usa “du/de la/des” para cantidades indefinidas, y “combien de” sirve tanto para contables como incontables (a diferencia del español «cuánto/cuántos»). En negativa, el partitivo se reduce a “de”.`},
14:{D:`La mayoría de los verbos franceses van seguidos de infinitivo (como en español); “en + gérondif” expresa simultaneidad o manera, y el participio presente (-ant) se usa más para describir.`},
15:{D:`El francés siempre expresa la posesión con “de + poseedor”, después del objeto poseído, como en español («el libro de Anna»); “de + les” se contrae en “des”.`},
16:{D:`Los pronombres de objeto directo (le, la, les) concuerdan en género y número con el sustantivo que reemplazan, y en francés van ANTES del verbo conjugado, igual que en español («la vi»).`},
17:{D:`Se usa el presente de indicativo (no el futuro) para hablar de horarios fijos de transporte, cine, tiendas, etc., ya que se consideran hechos programados, igual que en español.`},
18:{D:`Algunos verbos franceses van con una preposición fija que precisa su significado, de forma similar a verbos españoles como «pensar en» o «soñar con».`},
19:{D:`El tipo 0 (si + presente, presente) expresa verdades generales; el tipo 1 (si + presente, futuro) expresa una posibilidad real en el futuro. Como en español, nunca se usa el futuro justo después de “si”.`},
20:{T:`Coletillas invariables`,D:`Como en español («¿verdad?», «¿no?»), el francés usa coletillas invariables (n'est-ce pas, non, hein) que no cambian según el verbo, para casi cualquier oración.`},
21:{T:`Sin tiempo compuesto para la duración: presente + depuis`,D:`El francés no usa un tiempo compuesto para la duración (a diferencia de «llevar + gerundio» en español); para decir que algo acaba de pasar se usa “venir de + infinitivo” (presente), y para la duración de una acción que empezó en el pasado y continúa, se usa el PRESENTE + “depuis”.`},
22:{D:`A diferencia del español, TODOS los sustantivos en alemán llevan mayúscula inicial, no solo los nombres propios.`},
23:{D:`Bei Berufen benutzt "sein" keinen unbestimmten Artikel, genau wie im Spanischen (“Soy profesor”).`},
24:{D:`“Früher” + verbo en Präteritum expresa un hábito que ya no es cierto en el presente, similar a «antes + imperfecto» o «solía + infinitivo» en español.`},
25:{D:`“Außer wenn” o “wenn... nicht” expresan una condición negativa, equivalentes a «a menos que» en español.`},
26:{D:`“Könnte” (Konjunktiv II de “können”) expresa posibilidad en registro formal/legal, similar a «podría» (condicional de «poder») en español.`},
27:{D:`“Obwohl” + cláusula (verbo al final) introduce un contraste o concesión, equivalente a «aunque» o «a pesar de que» en español.`},
28:{D:`“Vorausgesetzt, dass” y “solange” expresan una condición necesaria, equivalentes a «siempre que» o «con tal de que» en español.`},
29:{D:`“Wäre da nicht” y “ohne” + sustantivo expresan una condición hipotética formal, equivalentes a «de no ser por» en español.`},
30:{D:`El alemán expresa una acción que empezó en el pasado y continúa usando el presente + “schon seit” + tiempo, de forma parecida a «llevar + gerundio» o «hace... que» en español.`},
31:{D:`“Kaum jemand ahnte” o “niemand hatte erwartet” al inicio enfatizan que algo fue una sorpresa total, equivalente a «pocos se imaginaban» o «nadie esperaba» en español.`},
32:{D:`“Zusätzlich zu” + sustantivo/gerundio nominal y “sowie” añaden información extra, similares a «además de» en español.`},
33:{D:`“Insofern als” e “insoweit” expresan una limitación o condición parcial, típicas del registro académico/formal, equivalentes a «en la medida en que» en español.`},
34:{D:`A diferencia del español y del francés (que usan «gustar»/«aimer» + infinitivo), en alemán se añade “gern” después del verbo conjugado para decir que te gusta hacer algo.`},
35:{D:`El alemán usa el presente + una expresión de tiempo para planes ya decididos (como el español «el sábado voy al cine»); “werden + infinitivo” se reserva para predicciones o promesas.`},
36:{D:`A diferencia del español («estaba + gerundio»), el alemán usa el Präteritum para ambas acciones; “gerade” enfatiza que una acción estaba en curso, y “als” introduce la acción que la interrumpe.`},
37:{D:`Los pronombres relativos alemanes (der/die/das) se declinan según género, número Y caso (nominativo, acusativo, dativo, genitivo) de su función dentro de la cláusula relativa; siempre llevan coma, a diferencia del español, donde la coma distingue la oración explicativa de la especificativa.`},
38:{D:`El alemán forma oraciones hendidas con “was...ist/war...” o “X war es, der/die...”, equivalentes a «lo que... es...» o «fue X quien...» en español.`},
39:{D:`Las construcciones de participio en alemán suenan formales/literarias; formas como “sich + adjetivo/participio + bewusst” reducen una cláusula causal más larga.`},
40:{D:`Con nombres propios, el alemán añade “-s” directamente: “Annas Buch” (en español, «el libro de Anna»). Con sustantivos comunes se usa el genitivo (“die Spielzeuge der Kinder”), pero en el habla “von + dativo” suele reemplazar al genitivo.`},
41:{D:`Algunos verbos alemanes van con una preposición fija que rige un caso específico, de forma similar a verbos españoles como «pensar en» o «soñar con».`},
43:{T:`Coletillas invariables`,D:`Como en español («¿verdad?», «¿no?»), el alemán usa coletillas invariables (nicht wahr?, oder?, stimmt's?) que no cambian según el verbo, para casi cualquier oración.`},
44:{T:`Sin tiempo compuesto para la duración: presente + seit`,D:`El alemán no usa un tiempo compuesto para la duración (a diferencia de «llevar + gerundio» en español); para la duración de una acción que empezó en el pasado y sigue en curso, se usa el PRESENTE + “seit” o “schon”, no una forma compuesta.`},
45:{D:`Con le professioni, "essere" non porta l'articolo indeterminativo, come in spagnolo (“Soy profesor”).`},
46:{D:`„Piacere” funziona come “gustar” in spagnolo: concorda con ciò che piace, non con la persona. Si usa con pronomi indiretti (mi, ti, gli/le, ci, vi, gli).`},
47:{D:`El futuro semplice expresa un plan o intención decidida, similar a «ir a + infinitivo» en español cuando el plan ya está claro.`},
48:{D:`El futuro anteriore (“avrà/sarà” + participio) también expresa una deducción o suposición sobre el pasado, equivalente a «habrá + participio» o «debe de haber» en español.`},
49:{D:`“Potrebbe” (condizionale de “potere”) expresa posibilidad en registro formal/legal, similar a «podría» (condicional de «poder») en español.`},
50:{D:`“Appena... che” expresa que una acción ocurrió inmediatamente después de otra, equivalente a «apenas... cuando» en español.`},
51:{D:`“Purché” y “a condizione che” + congiuntivo expresan una condición necesaria, equivalentes a «siempre que» o «con tal de que» en español.`},
52:{D:`“Se non fosse per” + sustantivo expresa una condición hipotética muy formal, equivalente a «de no ser por» en español.`},
53:{D:`El italiano expresa una acción que empezó en el pasado y continúa usando el presente + “da” + tiempo, de forma parecida a «hace... que» o «llevar + gerundio» en español.`},
54:{D:`“Pochi immaginavano” o “nessuno si aspettava” al inicio enfatizan que algo fue una sorpresa total, equivalente a «pocos se imaginaban» o «nadie esperaba» en español.`},
55:{D:`“Oltre a” + infinito o sustantivo y “così come” añaden información extra, similares a «además de» en español.`},
56:{D:`“Nella misura in cui” expresa una limitación o condición parcial, típica del registro académico/formal, equivalente a «en la medida en que» en español.`},
57:{D:`In italiano, come in spagnolo, non serve un ausiliare: basta la parola interrogativa + verbo (+ soggetto, spesso omesso).`},
58:{D:`A diferencia del español («hay», invariable), en italiano “c'è” (singular) y “ci sono” (plural) sí cambian según el número del sustantivo.`},
59:{D:`El italiano tiene una forma progresiva similar a la española («estaba + gerundio»): “stare” en imperfecto + gerundio para la acción de fondo, y el passato prossimo para la interrupción.`},
60:{D:`El italiano no invierte sujeto y verbo auxiliar, pero antepone adverbios negativos/restrictivos (“mai”, “appena”, “non solo”) al inicio de la oración para dar énfasis.`},
61:{D:`El italiano siempre expresa la posesión con “di + poseedor”, después del objeto poseído, como en español («el libro de Anna»); “di + i” se contrae en “dei”.`},
62:{D:`Algunos verbos italianos van con una preposición fija que precisa su significado, de forma similar a verbos españoles como «pensar en» o «soñar con».`},
64:{T:`Coletillas invariables`,D:`Como en español («¿verdad?», «¿no?»), el italiano usa coletillas invariables (vero?, no?, giusto?) que no cambian según el verbo, para casi cualquier oración.`},
65:{T:`Sin tiempo compuesto para la duración: presente + da`,D:`El italiano no usa un tiempo compuesto para la duración (a diferencia de «llevar + gerundio» en español); para la duración de una acción que empezó en el pasado y sigue en curso, se usa el PRESENTE + “da”, no una forma compuesta.`},
66:{D:`Com profissões, "ser" não leva artigo indefinido, tal como em espanhol (“Soy profesor”).`},
67:{D:`“Ir” + infinitivo expresa un plan o intención ya decidida, el equivalente a «ir a + infinitivo» en español.`},
68:{D:`El futuro composto (“terá” + participio) también expresa una deducción o suposición sobre el pasado, equivalente a «habrá + participio» o «debe de haber» en español.`},
69:{D:`“Embora” + subjuntivo introduce un contraste o concesión formal, equivalente a «aunque» en español.`},
70:{D:`“Mal... quando” expresa que una acción ocurrió inmediatamente después de otra, equivalente a «apenas... cuando» en español.`},
71:{D:`“Desde que” y “contanto que” + subjuntivo expresan una condición necesaria, equivalentes a «siempre que» o «con tal de que» en español.`},
72:{D:`“Se não fosse por” + sustantivo expresa una condición hipotética muy formal, equivalente a «de no ser por» en español.`},
73:{D:`“Poucos imaginavam” o “ninguém esperava” al inicio enfatizan que algo fue una sorpresa total, equivalente a «pocos se imaginaban» o «nadie esperaba» en español.`},
74:{D:`“Além de” + infinitivo o sustantivo y “assim como” añaden información extra, similares a «además de» en español.`},
75:{D:`“Na medida em que” expresa una limitación o condición parcial, típica del registro académico/formal, equivalente a «en la medida en que» en español.`},
76:{D:`Em português, como em espanhol, não é necessário um auxiliar: basta a palavra interrogativa + verbo (+ sujeito, muitas vezes omitido).`},
77:{D:`En portugués, el verbo que sigue a “gostar de”, “adorar” u “odiar” va en infinitivo, como en español («me gusta leer»). “Gostar” siempre lleva la preposición “de”.`},
78:{D:`El portugués usa “estar” en pretérito imperfeito + gerundio para la acción en curso (igual que el español «estaba + gerundio»), y el pretérito perfeito para la acción que la interrumpe.`},
79:{D:`El portugués de Brasil usa mucho “estar + gerundio” para el progresivo; la mayoría de los verbos con complemento verbal usan infinitivo, no gerundio (como en español).`},
80:{D:`El portugués no invierte sujeto y auxiliar, pero antepone adverbios negativos/restrictivos (“jamais”, “mal”, “não só”) al inicio de la oración para dar énfasis.`},
81:{D:`Como el español, el portugués tiene tres grados de distancia: “este” (cerca de mí), “esse” (cerca de ti), “aquele” (lejos de los dos).`},
82:{D:`El portugués siempre expresa la posesión con “de + poseedor”, después del objeto poseído, como en español («el libro de Ana»); “de + a” se contrae en “da”, “de + os” en “dos”.`},
83:{D:`Algunos verbos portugueses cambian de significado al combinarse con una preposición fija, de forma similar a verbos españoles como «pensar en» o «soñar con».`},
85:{T:null,D:`Como en español («¿verdad?», «¿no?»), el portugués usa coletillas invariables (não é?, né?, certo?) que no cambian según el verbo; “né?” es extremadamente común en el habla.`},
86:{T:`Sin tiempo compuesto para la duración: presente + há`,D:`El portugués de Brasil casi no usa una forma compuesta para la duración (a diferencia de «llevar + gerundio» en español); para la duración de una acción que sigue en curso, se usa el PRESENTE + “há”.`}
};
